cypress/e2e/groupTeachers.cy.js
https://trello.com/c/8JUMjHFr/58-at010001-name
=> AT_010.001 | Marketplace > Verify all links have the same color on the page

cypress/e2e/jScript_group.cy.js
https://trello.com/c/YQLMg3Za/62-at013001-navbar-blog
=> AT_013.001 | NavBar > Blog

cypress/e2e/jScript_group.cy.js
https://trello.com/c/YQLMg3Za/62-at013001-navbar-after-clicking-the-blog-menu-user-is-redirected-to-the-blog-page
=> AT_013.001 | NavBar > After clicking the Blog menu User is redirected to the Blog page

cypress/e2e/jScript_group.cy.js
https://trello.com/c/MaMmSOhZ/63-at002001-header-after-clicking-the-logo-user-is-redirected-to-the-home-page
=> AT_002.001 | Header > After clicking the logo user is redirected to the home page

cypress/e2e/jScript_group.cy.js
https://trello.com/c/ROuIICE6/84-at013002-navbar-after-redirecting-to-the-blog-page-10-posts-are-displayed-on-the-first-page
=> AT_013.002 | NavBar > After redirecting to the Blog page 10 posts are displayed on the first page

cypress/e2e/BugHunters.cy.js
https://trello.com/c/6bEj0mPr/70-at006001-main-page-sign-in
=> AT_006.001 | Main page > Sign in

cypress/e2e/jScript_group.cy.js
https://trello.com/c/ygC79gAz/135-at030001-footer-after-clicking-on-the-website-terms-and-conditions-in-the-footer-the-expected-page-is-opened
=> AT_030.001 | Footer > After clicking on the `Website terms and conditions` in the footer the expected page is opened

cypress/e2e/arkGroup.cy.js
https://trello.com/c/kjgW7jcO/121-tc010004-marketplace-verify-all-orange-links-on-the-page
=> AT_010.004 | Marketplace > Verify all orange links on the page

cypress/e2e/jScript_group.cy.js
https://trello.com/c/8IERhu89/210-at017002-name
=> AT_017.002 | Support > "How to start" > Verify "How to start" link redirection

cypress/e2e/noGroup.cy.js
https://trello.com/c/sG9h38x2/132-at010006-marketplaceverify-all-links-have-the-same-color-on-the-page
=> AT_010.006 | < Marketplace>Verify all links have the same color on the page

cypress/e2e/arkGroup.cy.js
AT_030.002 | Footer > After clicking on the Website terms and conditions user navigated to a new pdf file page
=> AT_030.002 | Footer > After clicking on the `Website terms and conditions` user navigated to a new pdf file page

cypress/e2e/BugHunters.cy.js
https://trello.com/c/4lxZxaWY/183-at029001-two-icons-download-on-the-app-store-and-get-it-on-google-play-are-visible
=> AT_029.001 | Two icons "Download on the App store" and "Get it on Google play" are visible

cypress/e2e/BugHunters.cy.js, cypress/e2e/jScript_group.cy.js
https://trello.com/c/ejIga6no/106-tc033002-header-navigation-verify-guide-menu-link
=> AT_033.002 | Header > Navigation > Verify "Guide" menu link

cypress/e2e/jScript_group.cy.js
https://trello.com/c/lXUgPe3e/219-at050001-footer-terms-and-conditions-of-sale
Verify "Terms and conditions of sale" link
=> AT_050.001 | Footer >Terms and conditions of sale

cypress/e2e/jScript_group.cy.js
https://trello.com/c/i6obv6fc/228-at012002-cms-verify-see-on-the-website-button
=> AT_012.002 | Partners > CMS > Verify "See on the website" button

cypress/e2e/jScript_group.cy.js
https://trello.com/c/mx4Lxytg/160-at002003-header-verifying-the-websites-logo-is-clickable-and-redirects-user-to-the-main-page
=> AT_002.003 | Header > Verifying the website's logo is clickable and redirects User to the Main page

cypress/e2e/jScript_group.cy.js
https://trello.com/c/XN2iK1bI/83-at031001-sign-in-account-dropdown-menu-after-cliking-the-logout-button-the-message-appears
=> AT_031.001 | Sign in > Account Dropdown Menu > After cliking the "logout" button the message appears

cypress/e2e/jScript_group.cy.js
https://trello.com/c/3vii8f6m/232-at022001-footer-verification-of-displayed-six-social-media-icons
=> AT_022.001 | Footer > Verification of displayed six Social Media icons

cypress/e2e/Reporter.cy.js
https://trello.com/c/d2OEdvNV/173-at001006-main-page-section-with-search-verify-text-message-when-entering-special-characters
=> AT_001.006 | Main page > Section with search > Verify text message when entering special characters

cypress/e2e/jScript_group.cy.js
https://trello.com/c/ReEt0L0J/236-at033001-header-navigation-verify-dashboard-menu-link
=> Add AT_033.001

cypress/e2e/jScript_group.cy.js
https://trello.com/c/ghEqirNW/178-tc008002-main-menu-guide-verify-the-first-button-learn-more-is-clickable-and-user-will-be-redirected-new-url
=> AT_008.002 | Main menu > Guide | Verify Learn More button

cypress/e2e/jScript_group.cy.js
https://trello.com/c/JIhafAsx/233-at022002-footer-ensure-facebook-icon-redirection
=> AT_022.002 | Footer > Ensure Facebook icon redirection

cypress/e2e/jScript_group.cy.js
https://trello.com/c/5iJyLH3Q/252-at012001-partners-cms-verifying-4-buttons-exist-in-the-section
=> AT_012.001 | Partners > CMS > Verifying 4 buttons exist in the section

cypress/e2e/ltByJs.cy.js
https://trello.com/c/VrF9PQzH/134-at033002-header-navigation-verify-guide-menu-link
=> AT_033.002 | Header > Navigation > Verify "Guide" menu item

cypress/e2e/Reporter.cy.js
https://trello.com/c/fWku6la2/92-at001001-main-page-section-with-search-verify-entered-a-zip-code-into-the-search-city-field
=> AT_001.001 | Main page > Section with search > Verify entered a Zip code into the Search city field

cypress/e2e/BugHunters.cy.js
https://trello.com/c/Sl94L0Ed/217-rf-groupbughunters-at006001-main-page-sign-in
=> RF | groupBugHunters > AT_006.001 | Main page > Sign in

cypress/e2e/ltByJs.cy.js
https://trello.com/c/yv4x1wlB/149-at002002-pricing-verifying-the-websites-logo-is-clickable-and-redirects-user-to-the-main-page
=> AT_002.002 | Pricing > Verifying the website"s logo is clickable and redirects User to the Main page'

cypress/e2e/ltByJs.cy.js
https://trello.com/c/6WX2s3PS/73-at009001-main-menu-after-clicking-marketplace-user-is-redirected-to-the-market-place-page
=> AT_009.001 | Main menu > After clicking Marketplace User is redirected to the Marketplace page

cypress/e2e/Reporter.cy.js
https://trello.com/c/BjFNB1ED/75-at005001-verify-the-website-name-and-description
=> AT_005.001 | Verify the website name and description

cypress/e2e/jScript_group.cy.js
https://trello.com/c/uDYaa3FE/277-at024001-main-page-different-weather-option-verify-email-enter
=> Add AT_024.001 Verify email enter

cypress/e2e/Reporter.cy.js
https://trello.com/c/hqFCJSr0/164-at034001-header-verify-for-business-button
=> AT_034.001 | <Header > verify "For Business" button

cypress/e2e/jScript_group.cy.js
https://trello.com/c/yWi4jik2/274-at012004-partners-cms-verify-view-widget-button
=>  AT_012.004 | Partners > CMS > Verify "View widget" button

cypress/e2e/group_javascript_for_qas.cy.js
…nauthorised user
https://trello.com/c/KjpOw5le/107-tc015002-header-support-ask-a-question-verify-alert-message-for-unauthorized-member
=> AT_015.002 | Support > Ask a question > Verify error for unauthorized user

cypress/e2e/jScript_group.cy.js
https://trello.com/c/xFobZHHz/139-at025006-main-menu-dashboard-verify-the-first-button-contact-us-is-clickable-and-redirect-user-to-new-url-questions
=> AT_025_06 | Main menu > Dashboard. Verify the first button "Contact us" is clickable and redirect user to new url "/questions"

cypress/e2e/arkGroup.cy.js
https://trello.com/c/YESIloB9/266-at018004-support-drop-down-menu-check-visible-link-and-verify-url
=> AT_018.004 | Support > Drop down menu. Check visible link and verify URL

cypress/e2e/BugHunters.cy.js
https://trello.com/c/ksRyKc0k/184-at029002-footer-download-openweather-app-download-on-the-app-store-button-link
=> AT_029.002 | Footer >Download OpenWeather App> Download on the App Store' button link

cypress/e2e/ltByJs.cy.js
https://trello.com/c/zOhMuInA/115-at009002-main-menu-marketplace-verification-of-displayed-content-history-bulk-and-its-price
=> AT_009.002 | Main menu > Marketplace verification of displayed content History bulk and it"s price'

cypress/e2e/ltByJs.cy.js
https://trello.com/c/7pBMzG4g/207-at031002-sign-in-account-dropdown-menu-verify-user-is-able-to-log-out
=> AT_031.002 | Sign In > Account Dropdown Menu > Verify user is able to log out

cypress/e2e/Reporter.cy.js
https://trello.com/c/qKYsTAVw/304-rf-reporter-at001006-main-page-section-with-search-verify-text-message-when-entering-special-characters
=> RF | Reporter > AT_001.006 | Main page > Section with search > Verify text message when entering special characters

cypress/e2e/ltByJs.cy.js
https://trello.com/c/tiAUJMeT/198-at001007-main-page-section-with-search-verify-entered-a-city-name-into-the-search-city-field
=> AT_001.007 | Main page > Section with search > Verify entered a City name into the Search city field

cypress/e2e/arkGroup.cy.js
https://trello.com/c/aENZUEHo/267-at028004-about-us-verify-buy-in-the-marketplace-button
=> AT_028.004 | About us, verify “Buy in the Marketplace” button

cypress/e2e/Reporter.cy.js
https://trello.com/c/xFFbJaRS/227-at001008-main-page-section-with-search-verify-entered-a-city-name-into-the-search-city-field
=> AT_001.008 | Main page > Section with search > Verify entered a City name into the Search city field

cypress/e2e/groupTeachers.cy.js
=> search city examples

cypress/e2e/ltByJs.cy.js
https://trello.com/c/Qt3dUVH5/278-at020001-sign-in-dropdown-menu-verify-dropdown-menu-options-exist
=> AT_020.001 | Sign in > Dropdown menu > Verify dropdown menu options exist

cypress/e2e/noGroup.cy.js
https://trello.com/c/VzqyccK1/309-at010007-tc010007-marketplace-verify-all-links-on-the-page-have-the-same-color
=> AT_010.007 | Marketplace > Verify all links on the page have the same color

cypress/e2e/jScript_group.cy.js
https://trello.com/c/KfFNHjfn/313-at012005-partners-cms-verify-view-plugin-button-for-wordpress-hd-weather-widget-by-the-waypoint
=> AT_012.005 | Partners > CMS > Verify “View plugin” button for WordPress HD Weather Widget by The Waypoint

cypress/e2e/ltByJs.cy.js
https://trello.com/c/f6Ugi8ex/245-at018001-support-drop-down-menu-verify-faq-menu-link
=> AT_018.001 | Support > Drop down menu > Verify "FAQ" menu link

cypress/e2e/Reporter.cy.js
AT_006.003 | Sign in > Verifying successful sign in
https://trello.com/c/Lw3sHb73/318-at006003-sign-in-verifying-successful-sign-in
=> AT_006.003 | Sign in > Verifying successful sign in

cypress/e2e/jScript_group.cy.js
https://trello.com/c/e8eP2jhe/327-at012006-partners-cms-verify-view-plugin-button-for-wordpress-wpcloudy-plugin
=> AT_012.006 | Partners > CMS > Verify “View plugin” button for WordPress WPCloudy Plugin

cypress/e2e/group_javascript_for_qas.cy.js
https://trello.com/c/aHM7WLak/93-at004001-main-page-verify-the-temperature-can-be-switched-from-imperial-to-metric
=> AT_004.001 |Main page >Verify the temperature can be switched from Imperial to Metric

cypress/e2e/ltByJs.cy.js
https://trello.com/c/OPf19HCO/246-at018002-support-drop-down-menu-verify-how-to-start-menu-link
=> AT_018.002 | Support > Drop down menu > Verify "How to start" menu link

cypress/e2e/ltByJs.cy.js
AT_018.003 | Support > Drop down menu > Verify "Ask a question" menu link
=> AT_018.003 | Support > Drop down menu > Verify "Ask a question" menu link

cypress/e2e/Reporter.cy.js
https://trello.com/c/2M50WRcN/315-at002009-header-clicking-the-logoverify-the-logo-and-redirected-to-the-main-page
=> AT_002.009|Header>Clicking-the-logo>Verify-the-logo-and-redirected-to-the-Main-page

cypress/e2e/Reporter.cy.js
https://trello.com/c/eAAmaHEY/272-at024002-after-clicking-on-send-button-the-form-window-automatically-disappears
=> AT_024.002 | After clicking on "send" button, the form window automatically disappears

cypress/e2e/jScript_group.cy.js
https://trello.com/c/0FD3pqOS/336-at002014-header-after-clicking-the-logo-user-is-redirected-to-the-main-page
=> AT_002.014 |  Header > After clicking the logo user is redirected to the main page

cypress/e2e/BugHunters.cy.js
https://trello.com/c/203NbsQ7/179-at029003-footer-download-openweather-app-download-on-the-google-play-button-link
=> AT_029.003 | Footer >Download OpenWeather App> Download on the Google play' button link

cypress/e2e/ltByJs.cy.js
https://trello.com/c/9jKjffdv/350-rf-ltbyjs-at018003-support-dropdown-menu-verify-ask-a-question-menu-link 
Delete "only" from the previously merged test(AT_018.003).
=> RF | ltByJs > AT_018.003 | Support > Dropdown menu > Verify "Ask a question" menu link'

cypress/e2e/ltByJs.cy.js
https://trello.com/c/3ktXMmL6/271-at033006-header-navigation-verify-partners-menu-link
=> AT_033.006 | Header > Navigation>> Verify "Partners" menu link

cypress/e2e/BugHunters.cy.js
https://trello.com/c/o3PhEo9V/221-at008007-main-menu-guide-verify-user-will-be-redirected-to-new-url-guide
=> AT_008.007 | Main menu > Guide > Verify user will be redirected to new url "/guide"

cypress/e2e/BugHunters.cy.js
https://trello.com/c/7wzngP04/295-at008004-main-menu-guide-verify-the-button-subscribe-to-one-call-by-call-is-clickable-and-user-be-redirected-new-url
=> AT_008.004 | Main menu > Guide | Verify the button "Subscribe to One Call by Call" is clickable and user be redirected new url

cypress/e2e/ltByJs.cy.js
https://trello.com/c/atWp7yZa/116-at009003-main-menu-marketplace-verification-of-displayed-content-history-bulk-and-buttons-documentation-and-place-order
=> AT_009.003 | Main menu > Marketplace verification of displayed content History bulk buttons "Documentation" and "Place order"'

cypress/e2e/jScript_group.cy.js
https://trello.com/c/XtBdsCOj/234-at022003-footer-verify-twitter-icon-redirection
=> AT_022.003 | Footer > Verify Twitter icon redirection

cypress/e2e/BugHunters.cy.js, cypress/e2e/bug
https://trello.com/c/dYV9LdGk/356-at027003-maps-section-with-the-scale-the-scale-in-the-lower-right-corner-changes-to-precipitation-mm-h
=> AT_027.003 | Maps > Section with the scale >The scale in the lower right corner changes to "Precipitation, mm/h".

cypress/e2e/jScript_group.cy.js
https://trello.com/c/GfO7Iosd/339-at033008-header-navigation-our-initiatives-menu-link
=> AT_033.008 | Header > Navigation > “Our Initiatives” menu link

cypress/e2e/arkGroup.cy.js
https://trello.com/c/98eBdfnV/321-at045003-main-page-section-with-8-day-forecast-detailed-weather-for-each-of-these-days-is-displayed
=> AT_045.003 | Main page > Section with 8-day forecast. Detailed weather for each of these days is displayed

cypress/e2e/jScript_group.cy.js
Add a new AT_002.012 | Header > Checking the website's logo is clickable and redirects User to the Main page
=> AT_002.012 | Header > Checking the website's logo

cypress/e2e/Reporter.cy.js
https://trello.com/c/2GIs7jzc/320-at033012-header-navigation-verify-maps-menu-link
=> AT_033.012 | Header > Navigation > Verify "Maps" menu link

cypress/e2e/jScript_group.cy.js
https://trello.com/c/dUnBbu16/380-at005002-main-page-verify-the-websites-description
=> AT_005.002 | Main page > Verify the website’s description

cypress/e2e/jScript_group.cy.js
https://trello.com/c/2y2sqCxi/136-at013003-blog-weather-verifying-the-first-posts-link-is-clickable-and-redirects-user-to-the-post-in-a-different-tab
=> AT_013.003 | Blog > Weather > Verifying the first post's link is clickable and redirects User to the post in a different tab

cypress/e2e/arkGroup.cy.js
https://trello.com/c/3LeluV48/366-tc023002-footer-faq-verify-faq-link-redirects-to-the-corresponding-page
=> AT_023.002 | Footer > FAQ > Verify "FAQ" link redirects to the corresponding page

cypress/e2e/jScript_group.cy.js
https://trello.com/c/vYaApUXL/386-at028006-footer-about-us-verify-products-documentation-button-redirects-to-the-expected-url
=> AT_028.006 | Footer > About us > Verify "Products Documentation" button redirects to the expected URL

cypress/e2e/Reporter.cy.js, cypress/fixtures/reporterFix.json
https://trello.com/c/oSFp81Gn/343-at024003-main-page-different-weather-option-verify-9-weather-icons-are-shown-and-their-text
=> AT_024.003 | Main page > "Different weather?" option > verify 9 weather icons are shown and their text

cypress/e2e/jScript_group.cy.js
https://trello.com/c/8FbxI3Oy/349-at028005-footer-about-us-verify-new-and-updates-button
=> AT_028.005 | Footer > About us > Verify "New and Updates" button

cypress/e2e/asiaJS.cy.js, cypress/e2e/jScript_group.cy.js
https://trello.com/c/Ik1OQrCz/403-at015001-header-support-ask-a-question-not-checking-ecaptcha-checkbox
=> AT_015.001 | Header > Support > Ask a question > Not checking eCAPTCHA checkbox

cypress/e2e/Reporter.cy.js
https://trello.com/c/flPNZfyi/398-at001002-main-page-section-with-search-search-city-on-clicking-the-search-button-dropdown-menu-with-relevant-options-appears
=> AT_001.002 | Main page > Section with search > Search City > On clicking the Search button, Dropdown menu with relevant options appears

cypress/e2e/group_javascript_for_qas.cy.js
=> AT_028.001 | Footer > About us > Verify "About us" link redirects to the corresponding page

cypress/e2e/asiaJS.cy.js
https://trello.com/c/DJ2gUsKL/406-err-asiajs-at003002-main-page-section-with-search-verify-the-converted-temperature-in-c-is-correct
=> ERR | asiaJS > AT_003.002 | Main page > Section with search > Verify the converted temperature in °C is correct

cypress/e2e/jScript_group.cy.js
https://trello.com/c/hHaAMXBW/405-at002011-header-clicking-the-logo-verify-the-main-page-is-opened-after-clicking-the-logo
=> AT_002.011  | Header > Clicking the logo > Verify the Main page is opened after clicking the logo.

cypress/e2e/arkGroup.cy.js
https://trello.com/c/wPFRu03i/224-at033005-header-navigation-verify-guide-menu-link
=> AT_033.005 | Header > Navigation - Verify "Guide" menu link

cypress/fixtures/jScript_group.json
https://trello.com/c/kgJYXqi0/410-rf-fixtures-create-fixture-file-for-jscriptgroup
=> RF | Fixtures > Create fixture file for jScript_group

cypress/e2e/jScript_group.cy.js
https://trello.com/c/XvdcT5zv/413-rf-jscriptgroup-add-beforeeach-and-refactor-tests
=> RF | jScript_group > Add beforeEach and refactor tests

cypress/e2e/group_javascript_for_qas.cy.js
https://trello.com/c/il8ZmKqp/358-at023001-footer-fqa-verify-faq-link-redirects-to-the-corresponding-page
=> AT_023.001 | Footer > FAQ > Verify "FAQ" link redirects to the corresponding page

cypress/e2e/group_javascript_for_qas.cy.js
https://trello.com/c/DKZk7KEc/412-at028001-refactoring-add-before-each-for-groupjavascriptforqas-class
=> AT_028.001 | Refactoring > Add before each for Group_JavaScript_for_qas class

cypress/e2e/ltByJs.cy.js
https://trello.com/c/NpD4mGOa/195-at022004-footer-check-medium-icon-is-clickable
=> AT_022.004 | Footer > Check Medium icon is clickable

cypress/e2e/BugHunters.cy.js
https://trello.com/c/fFxDzrq2/378-at033011-header-navigation-verify-api-menu-link
=> AT_033.011 | Header > Navigation > Verify "API" menu link'

cypress/e2e/jScript_group.cy.js
https://trello.com/c/EmXW0vKo/387-at033009-header-navigation-support-how-to-start-menu-link
=> AT_033.009 | Header > Navigation > Support > "How to start" menu link

cypress/e2e/BugHunters.cy.js
https://trello.com/c/on9IOfHf/424-at001013-main-page-search-section-verify-search-city-valid-input-shows-dropdown
=> AT_001.013 | Main page > Search section > Verify "Search City" valid input shows dropdown

cypress/e2e/arkGroup.cy.js
https://trello.com/c/DNYA9AEy/399-at045005-main-page-section-with-8-day-forecast-check-display-of-eight-days-from-current-date
=> AT_045.005 | Main page > Section with 8-day forecast. Check display of eight days from current date

cypress/e2e/ltByJs.cy.js
https://trello.com/c/HPJwYISz/415-rf-itbyjsgroup-main-menu-marketplace-verification-of-displayed-documentation-button-for-history-bulk
=> AT_009.003 | Main menu > Marketplace verification of displayed "Documentation" button for History bulk'

cypress/e2e/ltByJs.cy.js, cypress/fixtures/ItByJs_group.json
https://trello.com/c/KIONJDCe/428-rf-itbyjs-add-beforeeach-and-refactor-tests
=> RF | ItByJs > Add beforeEach and refactor tests

cypress/e2e/arkGroup.cy.js
https://trello.com/c/vc3N1SJP/372-at033010-header-navigation-verify-api-menu-link-name
=> AT_033.010 | Header > Navigation > Verify “API” menu link

cypress/e2e/jScript_group.cy.js
https://trello.com/c/QVcILDGA/414-at002010-header-clicking-the-logo-verify-that-the-logo-is-clickable
=> AT_002.010 Header > Clicking the logo > Verify that the logo is clickable

cypress/e2e/Reporter.cy.js
AT - https://trello.com/c/0sFu11La/167-at002005-guide-verifying-the-websites-logo-is-clickable-and-redirects-user-to-the-main-page
=> AT_002.005 | Guide > Verifying the website's logo is clickable and redirects User to the Main page

cypress/e2e/arkGroup.cy.js
https://trello.com/c/CDsu6jdk/370-at027002-maps-section-weather-control-scale-details-changes-when-switching-data-to-pressure
=> AT_027.002 | Maps > Section "weather control" > scale-details changes when switching data to Pressure

cypress/e2e/group_javascript_for_qas.cy.js, cypress/fixtures/group_javascript_for_qas.json
https://trello.com/c/ku59FUD0/79-at008001-main-menuverify-url-and-headers-are-displayed-on-the-page
=> AT_008.001 | Main menu > Guide > Verify URL and headers are displayed on the page

cypress/e2e/ltByJs.cy.js
https://trello.com/c/AACe2pEs/204-at014-002-support-ask-a-questioncheck-captcha-message
=> AT_014 .002| Support > Ask a question>Check captcha message

cypress/e2e/jScript_group.cy.js
https://trello.com/c/ZvlC6TUi/393-at033014-header-navigation-support-faq-menu-link
=> AT_033.014 | Header > Navigation > Support > "FAQ" menu link

cypress/e2e/jScript_group.cy.js, cypress/fixtures/jScript_group.json
https://trello.com/c/Uto7PEpN/440-rf-jscriptgroup-refactoring-tests
=> RF | jScript_group > Refactoring tests

cypress/e2e/Reporter.cy.js
https://trello.com/c/9LaM13DA/449-at001003-main-page-section-with-search-search-city-verify-a-user-is-able-to-select-a-city-from-the-search-results-dropdown
=> AT_001.003 | Main page > Section with search > Search City > Verify a user is able to select a city from the search results dropdown

cypress/e2e/Reporter.cy.js
https://trello.com/c/wIEq8Bl2/466-at016001-support-faq-page-verify-support-button-and-faq-link-is-clickable-and-redirects-to-the-faq-page
=> AT_016.001 | Support > FAQ page > Verify Support button and FAQ link is clickable and redirects to the FAQ page

cypress/e2e/jScript_group.cy.js
https://trello.com/c/92ebhWTb/467-rf-jscriptgroup-at015001-header-support-ask-a-question-not-checking-ecaptcha-checkbox
=> RF | jScript_group > AT_015.001 Header > Support > Ask a question > Not checking eCAPTCHA checkbox

cypress/e2e/jScript_group.cy.js
https://trello.com/c/Hi2Yyygi/460-at044001-footer-popups-manage-cookies
=> AT_044.001 | Footer > PopUps > Manage cookies

cypress/e2e/ltByJs.cy.js, cypress/fixtures/ItByJs_group.json
https://trello.com/c/EsUcGzE1/480-rf-itbyjs-at014-002-at001007-at031002-code-formatting
=> RF | ItByJs AT_014 .002, AT_001.007, AT_031.002 code formatting

cypress/e2e/BugHunters.cy.js
https://trello.com/c/2BtlgfTR/434-at009006-main-menu-marketplace
=> AT_009.006 Main menu > Marketplace 

cypress/e2e/asiaJS.cy.js
https://trello.com/c/EW4awQeV/482-at005005-main-page-verifying-the-websites-description-is-correct-and-visible
=> AT_005.005 | Main page > Verifying the website's description is correct and visible

cypress/e2e/asiaJS.cy.js
https://trello.com/c/BFczRxx1/369-at004003-main-page-section-with-search-verify-the-converted-temperature-in-c-is-correct
=> AT_004.003 | Main page > Section with search > Verify the converted temperature in °C is correct

cypress/e2e/jScript_group.cy.js
https://trello.com/c/eXZj4ZVk/90-at025002-main-menu-dashboard-after-clicking-the-first-try-the-dashboard-button-not-authorized-user-is-redirected-to-sign-in-page
=> AT_025.002 | Main menu > Dashboard > After clicking the first "Try the Dashboard" button not authorized User is redirected to Sign in page

cypress/e2e/bug
https://trello.com/c/MULnHs4d/489-rf-deleted-the-folder-bag
=> RF | Deleted the folder 'bug'

cypress/e2e/Reporter.cy.js
https://trello.com/c/gCPFkDbk/452-at001004-main-page-section-with-search-search-city-verify-weather-icon-and-current-weather-in-metric-system-are-displayed
=> AT_001.004 | Main page > Section with search > Search City > Verify weather icon and current weather in Metric system are displayed

cypress/e2e/ltByJs.cy.js
https://trello.com/c/2mh1pBQp/484-rf-itbyjsat002006-at021002-at033006-code-formatting
=> RF | ItByJs_AT_002.006, AT_021.002, AT_033.006 code formatting

cypress/e2e/arkGroup.cy.js
https://trello.com/c/ekiaj1Ph/438-at014004-support-ask-a-question-the-captcha-error-message-is-displayed
=> AT_014.004 | Support > Ask a question > The captcha error message is displayed

cypress/e2e/arkGroup.cy.js
https://trello.com/c/nWkRdRA3/451-rf010004-marketplace-verify-the-color-of-all-orange-links
=> AT_010.004 | Marketplace > Verify the color of all orange links

cypress/e2e/ltByJs.cy.js
https://trello.com/c/mckrpBXL/500-rf-itbyjs-delete-empty-lines
=> RF | ItByJs> delete empty lines

cypress/e2e/jScript_group.cy.js
https://trello.com/c/HSyIoEDS/394-at033015-header-navigation-support-ask-a-question-menu-link
=> AT_033.015 | Header > Navigation > Support > "Ask a question" menu link

cypress/e2e/BugHunters.cy.js
https://trello.com/c/AtWTxUc0/476-at032002-header-account-dropdown-menu-my-profile-password-change-verify-successful-notification
=> AT_032.002 | Header > Account Dropdown Menu > My Profile > Password Change> Verify successful notification

cypress/e2e/ltByJs.cy.js
https://trello.com/c/KV0WdYG2/307-at002008-dashboard-verifying-the-websites-logo-is-clickable-and-redirects-user-to-the-main-page
=> AT_002.008 | Dashboard > Verifying the website's logo is clickable and redirects User to the Main page

cypress/e2e/BugHunters.cy.js
https://trello.com/b/VzndwwBE/openweatherjs05
=> AT_009.007 | Main menu > Marketplace > Verification of displayed "Documentation" button for History bulk

cypress/e2e/BugHunters.cy.js, cypress/e2e/jScript_group.cy.js
https://trello.com/c/NwTuphAZ/302-at002007-header-verify-that-the-website-logo-is-clickable-and-the-user-is-redirected-to-the-main-page
=> AT_002.007 | Header > Verify that the website logo is clickable and the user is redirected to the Main Page

cypress/e2e/jScript_group.cy.js
https://trello.com/c/TFnjUzwV/506-at044002-footer-popups-manage-cookies-verify-cookies-settings
=> AT_044.002 | Footer > PopUps > Manage cookies > Verify Cookies Settings

cypress/e2e/jScript_group.cy.js
https://trello.com/c/lP03eXf2/507-at044003-footer-popups-manage-cookies-verify-allow-all-button
=> AT_044.003 | Footer > PopUps > Manage cookies > Verify Allow all button

cypress/e2e/jScript_group.cy.js
https://trello.com/c/Kr9f47KK/78-at025001-main-menu-after-clicking-the-dashboard-menu-user-is-redirected-to-the-dashboard-page
=> AT_025.001 | Main menu > After clicking the Dashboard menu User is redirected to the Dashboard page

cypress/fixtures/jScript_group.json
https://trello.com/c/qYDkzREq/512-rf-fixture-jscriptgroup-refactor-email
=> RF | Fixture/ jScript_group > Refactor email

cypress/e2e/jScript_group.cy.js
https://trello.com/c/4SSLD8KN/518-at013006-blog-weather-verify-that-after-clicking-the-blog-menu-a-user-is-redirected-to-the-blog-page-with-url
=> AT_013.006 | Blog > Weather > Verify that after clicking the Blog menu a user is redirected to the blog page

cypress/e2e/jScript_group.cy.js
https://trello.com/c/d0Fdl5tn/521-at025003-dashboard-verify-that-contact-us-button-redirects-the-user-to-ask-a-question-page
=> AT_025.003 | Dashboard > Verify that "Contact Us" button redirects the user to "Ask a question" page

cypress/e2e/Reporter.cy.js
https://trello.com/c/SaLzJ70D/475-at022008-name
=> AT_022.008 | Footer > Social media > Verify Github icon redirection

cypress/e2e/jScript_group.cy.js
https://trello.com/c/L1winAiT/430-at038001-for-business-page-verify-that-user-can-be-redirected-to-the-business-page
=> AT_038.001 | For business page > Verify that user can be redirected to the business page

cypress/e2e/jScript_group.cy.js
https://trello.com/c/8sVbZvVU/528-at013007-blog-weather-verify-that-after-landing-on-the-blog-page-10-posts-displayed-on-the-first-page
=> AT_013.007 | Blog > Weather > Verify that after landing on the Blog page 10 posts displayed on the first page

cypress/e2e/BugHunters.cy.js
https://trello.com/c/YZU8YEji/529-rf-added-beforeeach-in-the-folder-bughunters
=> RF | Added beforeEach() in the folder BugHunters.

cypress/e2e/BugHunters.cy.js
https://trello.com/c/jOVBtVa9/533-rf-removed-double-code
=> RF | Removed double code

cypress/e2e/BugHunters.cy.js
https://trello.com/c/0Su0kqdZ/539-at033016-header-clicking-on-guide-redirects-to-the-corresponding-url
=> AT_033.016 | Header > clicking on "Guide" redirects to the corresponding URL

cypress/e2e/arkGroup.cy.js
https://trello.com/c/RiqeJEKU/534-at029003-footer-download-openweather-app-get-it-on-google-play-button
=> AT_029.003 | Footer > Download OpenWeather app, " Get it on Google play" button

cypress/e2e/BugHunters.cy.js
https://trello.com/c/twDNdeoE/483-tc008009-main-menu-guide-verify-text-on-the-page
=> AT_008.009 | Main menu > Guide > Verify text on the page

cypress/e2e/ltByJs.cy.js
https://trello.com/c/oPMfRMfM/493-at025008-main-menu-dashboard-after-clicking-dashboard-item-on-bar-menu-user-is-redirected-to-dashboard-page
=> AT_025.008 | Main menu > Dashboard > After clicking "Dashboard" item on bar menu User is redirected to Dashboard page

cypress/e2e/ltByJs.cy.js, cypress/fixtures/ItByJs_group.json
https://trello.com/c/US8e25Sp/530-rf-itbyjs-at031002-code-formatting
=> RF | ItByJs > AT_031.002 code formatting

cypress/e2e/jScript_group.cy.js
https://trello.com/c/PIDodpfh/429-tc038002-for-business-page-about-us
=> AT_038.002 | For business page > Verify that  "About us"  reditect to the information business page.

cypress/e2e/BugHunters.cy.js
https://trello.com/c/atWp7yZa/116-at009005-main-menu-marketplace-verification-of-displayed-button-place-order-for-history-bulk
=> AT_009.008 | <Menu> Marketplace > Verification than "Place order" button is displayed and leads to URL

cypress/e2e/BugHunters.cy.js
https://trello.com/c/UW1wr5cC/549-at041001-verify-the-registered-user-is-redirected-to-the-my-api-keys-page
=> AT_041.001 | Verify the registered user is redirected to the My API keys 

cypress/e2e/BugHunters.cy.js
https://trello.com/c/j1sKDVlG/537-at056001-my-api-keys-managing-api-keys-verify-creation-and-deletion-of-an-api-key
=> AT_056.001 | My API keys > Managing API keys> Verify creation and deletion of an API key

cypress/e2e/Reporter.cy.js
AT_007.006 | Main page>Sign in> Create an account > "Lost your password? Click here to recover." checking.
=> AT_007.006 | Main page>Sign in> Create an account > "Lost your password? Click here to recover." checking.

cypress/e2e/noGroup.cy.js
=> AT_047.001 | User page > New Products > Check that an unauthorized user gets to the New Products page after logged in

cypress/e2e/ltByJs.cy.js
https://trello.com/c/lK1eLhvu/495-at025009-main-menu-dashboard-verify-the-first-button-try-the-dashboard-is-clickable-and-redirects-user-to-the-sign-in-page
=> AT_025.009 | Main menu > Dashboard > Verify the first button "Try the Dashboard" is clickable and redirects User to the Sign in page

cypress/e2e/jScript_group.cy.js, cypress/fixtures/jScript_group.json
https://trello.com/c/R3utO6qH/514-at027004-maps-section-with-the-scale-the-scales-name-matches-the-labels-name-after-selecting-pressure
=> AT_027.004 | Maps > Section with the scale > The scale's name matches the label's name after selecting "Pressure"

cypress/e2e/noGroup.cy.js, cypress/fixtures/noGroup.json
https://trello.com/c/tcqPcK2m/557-at043004-navbar-user-verify-that-tab-new-products-has-3-text-block
=> AT_043.004 | NavBar > User > Verify that tab "New Products" has 3 text-block

cypress/e2e/ltByJs.cy.js
https://trello.com/c/HMtdHm0I/262-at006002-sign-in-sign-in-to-your-account
=> AT_006.002 | Sign in > Sign in to Your Account

cypress/e2e/noGroup.cy.js
https://trello.com/c/8U9YZNq8/558-rf-nogroup-beforeeach-cyvisit-added-to-file
=> RF | noGroup > beforeEach (cy.visit) added to file

cypress/e2e/arkGroup.cy.js
https://trello.com/c/deTY8fYV/523-at026001-maps-check-that-global-precipitation-is-visualized-on-the-map
=> AT_026.001 | Maps > Check that Global Precipitation is visualized on the map

cypress/e2e/arkGroup.cy.js
https://trello.com/c/dJ0sa3mk/546-at033017-headernavigationapiverify-sign-up-link
=> AT_033.017 | Header>Navigation>API>Verify "sign up" link

cypress/e2e/BugHunters.cy.js, cypress/e2e/jScript_group.cy.js, cypress/fixtures/jScript_group.json
https://trello.com/c/p7zUkgFh/572-rf-jscriptgroup-at002001-header-after-clicking-the-logo-user-is-redirected-to-the-home-page
=> RF | jScript_group > AT_002.001 | Header > After clicking the logo user is redirected to the home page

cypress/e2e/noGroup.cy.js
https://trello.com/c/C0VSccdH/554-at043005-navbar-user-verify-that-title-of-3-text-blocks-on-the-home-page-have-the-same-color
=> AT_043.005 | NavBar > User > Verify that title of 3 text blocks on the home page have the same color

cypress/e2e/Reporter.cy.js
https://trello.com/c/OP9mUvf7/561-rf006003-sign-in-sign-in-to-your-account-verifying-successful-sign-in
=> RF_006.003 | Sign in > Sign in to Your Account> Verifying successful sign in

cypress/e2e/jScript_group.cy.js
=> RF | jScript_group > AT_012.001 | Partners > CMS > Verifying 4 buttons exist in the section

cypress/e2e/jScript_group.cy.js
https://trello.com/c/3kdLhQPa/567-ac010011-marketplace-verify-that-all-links-on-the-page-have-the-same-color
=> AC_010.011 |  Marketplace > Verify that all links on the page have the same color

cypress/e2e/jScript_group.cy.js
https://trello.com/c/6jX8R7Ny/142-at025005-main-menu-dashboard-verify-the-first-button-try-the-dashbord-is-clickable-and-redirect-user-to-new-url-users-signin
=> AT_025.005 | Header > Verify user will be redirected to new url "users/sign"

cypress/e2e/group_javascript_for_qas.cy.js
https://trello.com/c/jo6abfyy/569-at048001-user-page-billing-plans-verify-url-for-billing-plans
=> AT_048.001 | User page > Billing plans > Verify url for billing plans

cypress/e2e/asiaJS.cy.js
https://trello.com/c/03tT2uOQ/560-at005003-main-page-verify-the-website-name-and-description
=> AT_005.003 | Main page > Verify the website name and description

cypress/e2e/ltByJs.cy.js, cypress/fixtures/ItByJs_group.json
https://trello.com/c/uYEV8UXv/209-at021001-footer-widgetsinvalid-api
=> AT_021.001 | Footer > Widgets>Invalid API

cypress/e2e/BugHunters.cy.js
https://trello.com/c/JyitOZpd/607-at032003-header-account-dropdown-menu-my-profile-password-change-verify-successful-password-change
=> AT_032.003 | Header > Account Dropdown Menu > My Profile > Password Change > Verify successful password change

cypress/e2e/ltByJs.cy.js
https://trello.com/c/weo5oRyp/497-at025010-main-menu-dashboard-verify-the-first-button-contact-us-is-clickable-and-redirects-user-to-the-questions-page
=> AT_025.010 | Main menu > Dashboard > Verify the first button "Contact us" is clickable and redirects User to the Questions page

cypress/e2e/asiaJS.cy.js
https://trello.com/c/phVaEpKO/605-at045008-main-page-section-with-8-day-forecast-see-the-weather-forecast-for-8-days
=> AT_045.008 | Main page > Section with 8-day forecast > See the weather forecast for 8 days

cypress/e2e/BugHunters.cy.js
https://trello.com/c/TfptQI2d/541-at056002-my-api-keys-managing-api-keys-verify-rename-an-api-key
=> AT_056.002 | My API keys > Managing API keys> Verify rename an API key

cypress/e2e/asiaJS.cy.js
https://trello.com/c/ZFANUyKx/602-at046004-main-page-our-initiatives-button-learn-more-page-has-text-student-initiative
=> AT_046.004 | Main page > Our initiatives > button "Learn more" > page has text Student initiative

cypress/e2e/BugHunters.cy.js
https://trello.com/c/fAxClLWq/608-at027005-maps-section-with-the-scale-the-scales-name-matches-the-labels-name-after-selecting-wind-speed
=> AT_027.005 | Maps > Section with the scale > The scale's name matches the label's name after selecting "Wind speed"

cypress/e2e/ltByJs.cy.js
https://trello.com/c/9bDRT4md/609-rf-itbyjs-at021001-add-lines-between-steps
=> RF | ItByJs > AT_021.001 add lines between steps

cypress/e2e/ltByJs.cy.js
https://trello.com/c/lGFbzJiv/359-at033004-header-navigation-verify-marketplace-menu-link
=> AT_033.004 | Header > Navigation > Verify "Marketplace" menu link

cypress/e2e/BugHunters.cy.js
https://trello.com/c/qXNhSWFf/610-tc001016-main-page-section-with-search-search-city
=> AT_001.016 | Main page > Section with search > Search City

cypress/e2e/BugHunters.cy.js, cypress/e2e/jScript_group.cy.js, cypress/fixtures/jScript_group.json
https://trello.com/c/JJCAiBze/516-at045006-main-page-section-with-8-day-forecast-verifying-the-weather-forecast-for-8-days-is-displayed-in-the-section
=> AT_045.006 | Main page > Section with 8-day forecast > Verifying the weather forecast for 8 days is displayed in the section

cypress/e2e/BugHunters.cy.js, cypress/e2e/arkGroup.cy.js, cypress/fixtures/arkGroup.json
https://trello.com/c/MtYKpjK7/621-rf-arkgroup-formating-all-codes
=> RF | arkGroup > Formating all code

cypress/e2e/Reporter.cy.js
https://trello.com/c/eUZY9FLo/552-at008011-main-menu-guide-verify-button-home
=> AT_008.011 | Main menu > Guide > verify button "Home"

cypress/e2e/jScript_group.cy.js
https://trello.com/c/ya6NPFow/519-at045007-main-page-section-with-8-day-forecast-verifying-the-first-displayed-day-in-the-section-matches-todays-date
=> AT_045.007 | Main page > Section with 8-day forecast > Verifying the first displayed day in the section matches today's date

cypress/e2e/arkGroup.cy.js
https://trello.com/c/f0MbBbYL/612-tc054002-personalaccountname-verify-successful-sign-out
=> AT_054.002 | PersonalAccountName > Verify a successful Sign out

cypress/e2e/jScript_group.cy.js, cypress/fixtures/jScript_group.json
https://trello.com/c/eFZaMqAR/170-tc0280002-footer-about-us-verify-contact-us-button-redirects-user-to-questions-page
=> AT_028.0002 | Footer > About us > Verify "Contact us" button redirects user to "Questions" page

cypress/e2e/jScript_group.cy.js
https://trello.com/c/ErRqAzkC/624-at021003-footer-verify-there-are-9-widgets-on-the-page
=> AT_021.003 | Footer > Verify there are 9 widgets on the page

cypress/e2e/arkGroup.cy.js, cypress/fixtures/arkGroup.json
https://trello.com/c/91fD6En6/620-at044004-footer-popups-manage-cookies-verify-the-background-color-of-a-button-and-link-when-the-element-is-in-mouse-focus
=> AT_044.004 | Footer > PopUps > Manage cookies > Verify the background color of a button and link when the element is in mouse focus

cypress/e2e/noGroup.cy.js
https://trello.com/c/IizNjark/614-rf-nogroup-transferring-variables-to-describe-part
=> RF | noGroup > transferring variables to Describe part

cypress/e2e/BugHunters.cy.js
https://trello.com/c/O4DZKveM/627-err-bughunters-at056002-my-api-keys-managing-api-keys-verify-rename-an-api-key
=> ERR | BugHunters > AT_056.002 | My API keys > Managing API keys> Verify rename an API key

cypress/e2e/noGroup.cy.js
https://trello.com/c/JKuOml5X/613-at006005-sign-in-sign-in-to-your-account-verify-that-after-the-user-fills-in-the-wrong-password-the-alert-pop-up-appears
=> AT_006.005 | Sign in > Sign in to Your Account > Verify that after the user fills in the wrong password the alert pop-up appears

cypress/e2e/jScript_group.cy.js
https://trello.com/c/3nRej1yh/447-at010008-marketplace-verify-the-link-history-bulk-on-the-page
=> AT_010.008 | Marketplace > Verify the link "History Bulk” on the page

cypress/e2e/jScript_group.cy.js
https://trello.com/c/OBkmkGyJ/642-at021004-footer-widgets-the-widgets-code-is-visible
=> AT_021.004 | Footer > Widgets > The widget's code is visible

cypress/e2e/jScript_group.cy.js
https://trello.com/c/0jgPalZ5/556-at014003-support-ask-a-questionverify-if-the-ask-the-question-page-opens
=> AT_014.003  Support > Ask a question>Verify if the "Ask the question" page open

cypress/e2e/BugHunters.cy.js
https://trello.com/c/s85o78gI/417-at046002-our-initiatives-initiative-articles-on-the-pageclick-on-the-link-learn-more-should-take-user-to-the-new-page
=> AT_046.002 | Our initiatives > Initiative articles on the page>Click on the link “Learn more” should take user to the new page

cypress/e2e/arkGroup.cy.js
https://trello.com/c/AUbdXzCN/650-at026003-maps-%D1%81heck-that-the-zoom-in-button-works
=> AT_026.003 | Maps > Сheck that the "Zoom in" button works

cypress/e2e/jScript_group.cy.js
https://trello.com/c/dTF4yy3I/626-at014004-support-ask-a-question-an-error-message-of-the-recapcha
=> AT_014.004 | Support > Ask a question> An error message of the reCAPCHA

cypress/e2e/asiaJS.cy.js
https://trello.com/c/8h6UoBSb/646-at016002-support-faq-page-verify-the-question-how-to-get-an-api-key-is-opened-and-visible-by-clicking-on-it
=> AT_016.002 | Support > FAQ page > Verify the question "How to get an API key" is opened and visible by clicking on it

cypress/e2e/jScript_group.cy.js
https://trello.com/c/4qPx6bHy/643-rf-jscriptgroup-tc012002-add-aliases-to-all-links
=> RF | jScript_group > AT_012.002 add aliases to all links

cypress/e2e/jScript_group.cy.js
https://trello.com/c/7FU9Ejdw/649-rf-jscriptgroup-024001-main-page-different-weather-option-verify-email-enter
=> RF | jScript_group > AT_024.001 add assertion

cypress/e2e/jScript_group.cy.js
https://trello.com/c/El0BkyPK/660-rf-jscriptgroup-at012004-add-aliases-to-all-links
=> RF | jScript_group > AT_012.004 add aliases to all locators

cypress/e2e/arkGroup.cy.js
https://trello.com/c/8gpZyNMb/658-at-049001-user-page-blocked-logs-the-page-is-loading-and-displaying
=> AT_049.001 | User page > Blocked logs > The page is loading and displaying

cypress/e2e/ltByJs.cy.js, cypress/fixtures/ItByJs_group.json
https://trello.com/c/JqlbZkpG/196-at007002-create-an-account-check-message-error
=> AT_007.002 |Create an account> Check message error

cypress/e2e/ltByJs.cy.js
https://trello.com/c/EFrtWEH1/200-at004004-main-page-section-with-search-switching-weather-to-metric-system
=> AT_004.004 | Main page > Section with search > Switching weather to Metric system

cypress/e2e/arkGroup.cy.js
https://trello.com/c/Gq6WhjP8/659-rf-arkgroup-at026003-maps-%D1%81heck-that-the-zoom-in-button-works
=> RF | arkGroup > AT_026.003 | Maps > Сheck that the "Zoom in" button works

cypress/e2e/noGroup.cy.js
https://trello.com/c/G5Jhwy5R/420-at001012-main-page-section-with-search-search-city-the-displayed-city-name-equals-the-city-selected-in-the-search-city-field
=> AT_001.012 | Main page > Section with search > Search City> The displayed city name equals the city selected in the 'Search city' field

cypress/e2e/BugHunters.cy.js
https://trello.com/c/O4XgyJ4g/676-at005006-verifying-the-websites-name-and-description
=> AT_005.006 | Verifying the website's name and description

cypress/e2e/asiaJS.cy.js, cypress/fixtures/asiaJS.json
https://trello.com/c/NOOzj6ea/656-at042005-user-page-my-paymentsverify-that-text-displays-on-the-page
=> AT_042.005 | User page >My payments>Verify that text displays on the page

cypress/e2e/group_javascript_for_qas.cy.js, cypress/fixtures/group_javascript_for_qas.json
https://trello.com/c/Ey4I0BkE/404-at005004verify-the-websites-name-and-description-is-correct-and-visible
=> AT_005.004Verify the website’s name and description is correct and visible

cypress/e2e/BugHunters.cy.js, cypress/fixtures/bugHunters.json
https://trello.com/c/LFtsgmUP/684-at020004-sign-indropdown-menuverify-dropdown-menu-is-visible-and-exist
=> AT_020.004 | Sign in>Dropdown menu>Verify dropdown menu is visible and exist

cypress/e2e/noGroup.cy.js
https://trello.com/c/3vIYQuLH/686-at048004-user-page-billing-plans-verify-that-after-the-user-clicks-on-the-link-one-call-by-call-subscription-plan-open-a-new-pag
=> AT_048.004 | User page > Billing plans > Verify that after the user clicks on the link "One Call by Call" subscription plan" open a new page url

cypress/e2e/Reporter.cy.js
https://trello.com/c/evJaFy0O/566-at051004-api-testing-home-button-verify-that-after-clicking-on-the-home-link-on-the-api-page-the-user-gets-redirected-to-the-hom
=> AT_051.004 | API > Testing Home button. Verify that after clicking on the Home link on the API page the user gets redirected to the Home page.

cypress/e2e/group_javascript_for_qas.cy.js
https://trello.com/c/DNhAPlLm/699-rf-groupjavascriptforqas-at015002-header-support-ask-a-question-implements-variables
https://trello.com/c/uthbK1a7/703-rf-groupjavascriptforqas-tc008001-main-menu-guide-verify-url-and-header-is-displayed-on-the-page-splitting-into-two-tc-and-at
=> RF | group_javascript_for_qas > AT_015.002 implementing variables ,  AT_008.001 was split into AT_008.001 and AT_008.012  

cypress/e2e/jScript_group.cy.js
https://trello.com/c/9n3kSmBi/526-at048002-user-page-billing-plans-verify-billing-plans-information
=> AT_048.002 | User page > Billing plans > Verify billing plans information

cypress/e2e/OLD/asiaJS.cy.js, cypress/support/commands.js
https://trello.com/c/Zt7SvSCW/689-at048003-myservices-billing-plans-verify-billing-plans-are-present
=> AT_048.003 | Myservices > Billing plans > Verify billing plans are present

cypress/e2e/OLD/jScript_group.cy.js
https://trello.com/c/SOr6bHhQ/719-rf-jscriptgroup-whole-spec
=> RF | jScript_group > Base URL and Force True

cypress/e2e/OLD/noGroup.cy.js
https://trello.com/c/2mZVSPiH/728-rf-nogroup-code-optimization
=> RF | noGroup > code optimization

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/partnersPageSpec.cy.js, cypress/fixtures/partnersPage.json, cypress/pageObjects/Header.js, cypress/pageObjects/PartnersPage.js
https://trello.com/c/EMsBOUdg/733-rf-partnerspagespec-at012001-partners-cms-verifying-4-buttons-exist-in-the-section
=> RF | partnersPageSpec > AT_012.001 | Partners > CMS > Verifying 4 buttons exist in the section

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/blogPageSpec.cy.js, cypress/fixtures/blogPage.json, cypress/pageObjects/BlogPage.js
https://trello.com/c/3C3cwQur/732-rf-blogpagespec-at013003-blog-weather-verifying-the-first-post-s-link-is-clickable-and-redirects-user-to-the-post-on-a-new-page
=> RF | blogPageSpec > AT_013.003 | Blog > Weather > Verifying the first post's link is clickable and redirects User to the post on a new page

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/mainPageSpec.cy.js, cypress/fixtures/mainPage.json, cypress/pageObjects/MainPage.js
https://trello.com/c/sGZn9NqF/725-rf-mainpagespec-at005002-verify-the-websites-description
=> RF | mainPageSpec > AT_005.002 Verify the website’s description

cypress/e2e/OLD/BugHunters.cy.js
https://trello.com/c/TJaQNGJg/672-at041003-header-user-my-api-keys-you-can-generate-the-keys-message-is-visible
=> newest update

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/questionsPageSpec.cy.js, cypress/fixtures/questionsPage.json, cypress/pageObjects/Header.js, cypress/pageObjects/QuestionsPage.js
https://trello.com/c/10kWXFaI/727-rf-questionspagespec-at015001-not-checking-ecaptcha-checkbox
=> RF | questionsPageSpec > AT_015.001 Not checking eCAPTCHA checkbox

cypress/e2e/OLD/asiaJS.cy.js
https://trello.com/c/Tg21AAUx/655-at013009-blog-weather-all-posts-links-are-clickable-and-redirect-a-user-to-the-posts-in-a-new-page
=> AT_013.009 | Blog > Weather > All post's links are clickable and redirect a user to the posts in a new page

cypress/e2e/OLD/asiaJS.cy.js, cypress/fixtures/asiaJS.json
https://trello.com/c/FSEKtDTJ/723-at045009-main-page-section-with-8-day-forecast-detailed-weather-for-each-of-these-days-is-displayed
=> AT_045.009 | Main page > Section with 8-day forecast > Detailed weather for each of these days is displayed

cypress/e2e/OLD/BugHunters.cy.js
https://trello.com/c/Lyipf5Tx/707-at021005-footer-widgets-verify-redirect-to-widgets-constructor-page
=> AT_021.005 | Footer > Widgets> Verify redirect to Widgets constructor page

cypress/e2e/OLD/BugHunters.cy.js, cypress/e2e/footerSpec.cy.js, cypress/pageObjects/Footer.js
https://trello.com/c/cz4heKVe/744-rf-footerspec-at029001-footer-download-openweather-app-verify-two-icons-are-visible
=> RF | FooterSpec > AT_029.001 | Footer >Download OpenWeather App> Verify two icons are visible

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/mapsPageSpec.cy.js, cypress/fixtures/mapsPage.json, cypress/pageObjects/Header.js, cypress/pageObjects/MapsPage.js
https://trello.com/c/yj2pfqFV/736-rf-mapspagespec-testname
=> RF | mapsPageSpec > AT_027.004 | Maps > Section with the scale > The scale's name matches the label's name after selecting "Pressure"

cypress/e2e/OLD/BugHunters.cy.js
https://trello.com/c/HYPD6UdL/714-at028008-footer-about-us-verify-the-button-buy-by-subscriptions
=> AT_028.008 | Footer > About us > Verify the button "Buy by Subscription"

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/mainPageSpec.cy.js, cypress/fixtures/mainPage.json, cypress/pageObjects/MainPage.js
https://trello.com/c/AlGODhkM/751-rf-mainpagespec-testname
=> RF | mainPageSpec > AT_045.006 | Main page > Section with 8-day forecast > Verifying the weather forecast for 8 days is displayed in the section

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/mainPageSpec.cy.js, cypress/pageObjects/MainPage.js
https://trello.com/c/IL9LxmA9/754-rf-mainpagespec-testname
=> RF | mainPageSpec > AT_045.007 | Main page > Section with 8-day forecast > Verifying the first displayed day in the section matches today's date

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/marketplacePageSpec.cy.js, cypress/fixtures/marketplace.json, cypress/fixtures/marketplacePage.json, cypress/pageObjects/MarketplacePage.js
https://trello.com/c/fpP0MKlC/737-at010011-marketplace-verify-that-all-links-on-the-page-have-the-same-color
=> RF | marketplacePageSpec > AT_010.011 | Marketplace > Verify that all links on the page have the same color

cypress/e2e/footerSpec.cy.js, cypress/fixtures/footer.json, cypress/pageObjects/Footer.js
https://trello.com/c/v8KeSABj/761-rf-footer-after-clicking-on-the-website-terms-and-conditions-in-the-footer-the-expected-page-is-opened-2
Add clickWebsiteTermsAndConditions method;
Change '*' to '$' in CSS locator;
Remove unused fixture in footer fixtures;
=> RF | footerSpec > AT_030.001 Footer > After clicking on the "Website terms and conditions" in the footer the expected page is opened'

cypress/e2e/OLD/BugHunters.cy.js
https://trello.com/c/2CnIFcHT/306-at001011-main-page-section-with-search-selected-city-wheather-info-is-displayed
=> add teAT_001.011 |Main page > Section with search >Selected city wheather info is displayedst

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/aboutUsPageSpec.cy.js, cypress/fixtures/url.json, cypress/pageObjects/AboutUsPage.js, cypress/pageObjects/ApiPage.js, cypress/pageObjects/Footer.js
https://trello.com/c/LFUrtWvO/763-rf-specname-testname
=> RF | AboutUsPageSpec > AT_028.006 | About us > Verify "Products Documentation" button redirects to API page

cypress/e2e/OLD/noGroup.cy.js
https://trello.com/c/b4PrbC9G/745-at028009-footer-about-us-verify-the-button-buy-in-the-marketplace-redirects-to-the-expected-page
=> AT_028.009 | Footer > About us > Verify the button "Buy in the Marketplace" redirects to the expected page

cypress/e2e/our_InitiativesSpec.cy.js, cypress/fixtures/mainPage.json, cypress/pageObjects/Header.js
https://trello.com/c/ZKdE0ipa/750-rf-initiatives-spec-at002006-our-initiatives-verifying-the-websites-logo-is-clickable-and-redirects-user-to-the-main-page
=> RF | Initiatives Spec > AT_002.006 | Our Initiatives > Verifying the website's logo is clickable and redirects User to the Main page

cypress/e2e/OLD/arkGroup.cy.js
https://trello.com/c/cNSpvs07/762-rf-arkgroup-at028007-footer-about-us-verify-the-where-to-text
=> RF | arkGroup > AT_028.007 |< Footer > About us, verify the “Where-to” text

cypress/e2e/OLD/BugHunters.cy.js
https://trello.com/c/eTWItegR/752-rf-005-main-page-changing-code-in-folder-bughunters-on
=> RF | groupBugHunters > Refactoring using baseUrl from config

cypress/e2e/OLD/BugHunters.cy.js, cypress/e2e/footerSpec.cy.js, cypress/fixtures/footer.json, cypress/pageObjects/Footer.js
https://trello.com/c/JKUAH43g/764-rf-widgetspagespec-at021003-footer-verify-there-are-9-widgets-on-the-page
=> RF | widgetsPageSpec > AT_021.003 | Footer > Verify there are 9 widgets on the page

cypress/e2e/OLD/noGroup.cy.js, cypress/e2e/userHomePageSpec.cy.js, cypress/fixtures/userHomePage.json, cypress/pageObjects/UserHomePage.js
https://trello.com/c/qbZKz93x/769-rf-userhomepagespec-at043005-navbar-user-verify-that-title-of-3-text-blocks-on-the-home-page-have-the-same-color
=> RF | userHomePageSpec > AT_043.005 | NavBar > User > Verify that title of 3 text blocks on the home page have the same color

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/mainPageSpec.cy.js, cypress/fixtures/url.json
https://trello.com/c/Cn6RLqYk/773-rf-mainpagespec-at002001-header-after-clicking-the-logo-user-is-redirected-to-the-home-page
=> RF |  mainPageSpec > AT_002.001 | Header > After clicking the logo user is redirected to the home page

cypress/e2e/OLD/ltByJs.cy.js, cypress/e2e/marketplacePageSpec.cy.js, cypress/fixtures/historybulk.json, cypress/fixtures/url.json, cypress/pageObjects/HistoryBulkPage.js, cypress/pageObjects/MarketplacePage.js
https://trello.com/c/sfTCCldD/774-rf-at009003-main-menu-marketplace-verification-of-displayed-documentation-button-for-history-bulk
=> RF | AT_009.003 >Main menu > Marketplace verification of displayed "Documentation" button for History bulk

cypress/e2e/OLD/BugHunters.cy.js
https://trello.com/c/V1gzRONp/332-at051001-api-testing-home-buttonverify-home-link-is-visible-on-the-right-upper-side-of-the-page
=> AT_051.001 API > Testing Home button>Verify Home link is visible on the right upper side of the page

cypress/e2e/OLD/BugHunters.cy.js
https://trello.com/c/aWgpBVDz/766-rf-edittest-at056001-my-api-keys-managing-api-keys-create-new-api-key
=> RF | BugHunters > AT_056.001 | My API keys > Managing API keys> Create new API key

cypress/e2e/OLD/BugHunters.cy.js
https://trello.com/c/N6mlu0ls/767-rf-edittest-at056002-my-api-keys-managing-api-keys-rename-an-api-key
=> RF | BugHunters > AT_056.002 | My API keys > Managing API keys> Rename an API key

cypress/e2e/OLD/asiaJS.cy.js, cypress/e2e/footerSpec.cy.js, cypress/fixtures/url.json
https://trello.com/c/6hIt4kF6/778-rf-footerspec-at030003-footer-website-terms-and-conditions-verify-redirecting-to-new-url
=> RF | footerSpec > AT_030.003 | Footer > Website terms and conditions > Verify redirecting to new url

cypress/e2e/OLD/noGroup.cy.js, cypress/e2e/userHomePageSpec.cy.js, cypress/pageObjects/UserHomePage.js
https://trello.com/c/Dc4PQJbO/771-rf-userhomepage-at043004-navbar-user-verify-that-tab-new-products-has-3-text-block
=> RF | userHomePage > AT_043.004 | NavBar > User > Verify that tab "New Products" has 3 text-block

cypress/e2e/OLD/asiaJS.cy.js, cypress/e2e/guidePageSpec.cy.js, cypress/fixtures/asiaJS.json, cypress/pageObjects/GuidePage.js, cypress/pageObjects/Header.js
https://trello.com/c/3fTmaBeR/783-rf-guidepagespec-at008003-main-menu-guide-verifying-the-link-on-the-page-guide
=> RF | GuidePageSpec > AT_008.003 > Main menu > Guide > Verifying the link on the page "Guide"

cypress/e2e/OLD/BugHunters.cy.js
https://trello.com/c/QY9h1ZYr/782-https-openweathermaporg-technology
=> AT_017.004 | Support > How to start > Verify the newly opened page title is Technology

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/mainPageSpec.cy.js, cypress/pageObjects/MainPage.js
https://trello.com/c/UJFzOIXs/776-rf-mainpage-at045001pom8-days-are-displayed
=> RF | MainPage > AT_045.001>POM_8 days are displayed

cypress/e2e/OLD/BugHunters.cy.js, cypress/e2e/footerSpec.cy.js, cypress/pageObjects/Footer.js
https://trello.com/c/kAXxaNiB/765-rf-footerspec-at029003-footer-download-openweather-app-download-on-the-google-play-button-link
=> RF | FooterSpec > AT_029.003 | Footer >Download OpenWeather App> Download on the Google play' button link

cypress/e2e/OLD/BugHunters.cy.js, cypress/e2e/OLD/noGroup.cy.js, cypress/e2e/userHomePageSpec.cy.js, cypress/pageObjects/UserHomePage.js
https://trello.com/c/XSEAFAUX/770-rf-userhomepage-tc043002-navbar-user-my-profile-verify-that-navbar-has-9-options
=> RF | userHomePage > TC_043.002 | NavBar > User > My profile > Verify that NavBar has 9 options

cypress/e2e/dashboardPageSpec.cy.js, cypress/fixtures/dashboardPage.json, cypress/pageObjects/DashboardPage.js, cypress/pageObjects/Header.js
https://trello.com/c/Wp5TtCbF/787-rf-dashboardpagespec-033001-header-navigation-verify-dashboard-menu-link
=> RF | DashboardPageSpec > AT_033.001 |Header > Navigation > Dashboard"

cypress/e2e/OLD/BugHunters.cy.js, cypress/e2e/guidePageSpec.cy.js, cypress/fixtures/url.json
https://trello.com/c/CwEMhF63/793-rf-guidepagename-testname
=> RF | guidePageSpec > AT_008.007 | Main menu > Guide > Verify user will be redirected to new url "/guide"

cypress/e2e/OLD/noGroup.cy.js
https://trello.com/c/tLOIDgYx/785-rf-nogroup-at028009-footer-about-us-verify-the-button-buy-in-the-marketplace-redirects-to-the-expected-page
=> RF | noGroup> AT_028.009 | Footer > About us > Verify the button "Buy in the Marketplace" redirects to the expected page

cypress/e2e/OLD/ltByJs.cy.js, cypress/e2e/footerSpec.cy.js, cypress/fixtures/footer.json, cypress/fixtures/url.json, cypress/pageObjects/Footer.js
https://trello.com/c/DpBav6aB/797-rf-footerspec-at022004-footer-check-medium-icon-is-clickable
=> RF |FooterSpec > AT_022.004 | Footer > Check Medium icon is clickable

cypress/e2e/OLD/arkGroup.cy.js, cypress/e2e/marketplacePageSpec.cy.js, cypress/pageObjects/MarketplacePage.js
https://trello.com/c/tDQU7bib/798-rf-marketplacepagespec-at010004-marketplace-verify-the-color-of-all-orange-links
=> RF | marketplacePageSpec > AT_010.004 | Marketplace > Verify the color of all orange links

cypress/e2e/questionsPageSpec.cy.js, cypress/pageObjects/Header.js
https://trello.com/c/iYEr2q7M/801-rf-questionspagespecat015001andupdateheaderpage
=> RF | questionsPageSpec_AT_015.001_and_update_headerPage

cypress/e2e/userHomePageSpec.cy.js, cypress/pageObjects/Header.js, cypress/pageObjects/UserServicesPage.js
=> AT_047.002 | User page > New Products > Check that authorized user can get to the New Products page

cypress/e2e/userHomePageSpec.cy.js, cypress/fixtures/url.json
=> RF | userHomePage > AT_047.001, AT_047.002 

cypress/e2e/OLD/asiaJS.cy.js, cypress/e2e/faqPageSpec.cy.js, cypress/fixtures/faqPage.json, cypress/pageObjects/FAQPage.js
https://trello.com/c/P4Qy6xea/803-rf-faqpagespec-at016002-faq-page-verify-the-question-how-to-get-an-api-key-is-opened-and-visible
=> RF | faqPageSpec > AT_016.002 |  FAQ page > Verify the question "How to get an API key" is opened and visible

cypress/e2e/mainPageSpec.cy.js, cypress/fixtures/mainPage.json
https://trello.com/c/tNMs5J5l/784-rf-mainpagespec-at001014-main-page-section-with-search-search-city-verify-that-entered-city-is-displayed-into-the-dropdown
=> RF | mainPageSpec > AT_001.014 | Main page > Section with search > Search City > Verify that entered city is displayed into the dropdown

cypress/e2e/OLD/BugHunters.cy.js, cypress/e2e/widgetsPageSpec.cy.js, cypress/fixtures/footer.json, cypress/fixtures/widgetsPage.json, cypress/pageObjects/Footer.js, cypress/pageObjects/WidgetsPage.js
https://trello.com/c/3Jd89IyQ/806-rf-widgetspagespec-at021005-footer-widgets-verify-redirect-to-widgets-constructor-page
=> RF | WidgetsPageSpec > AT_021.005 | Footer > Widgets> Verify redirect to Widgets constructor page

cypress/e2e/OLD/arkGroup.cy.js
https://trello.com/c/BjtXAEVQ/704-rf-arkgroup-at045005-main-page-section-with-8-day-forecast-check-display-of-eight-days-from-current-date
=> RF | arkGroup > AT_045.005 | Main page > Section with 8-day forecast > Check display of eight days from current date

cypress/e2e/OLD/arkGroup.cy.js, cypress/e2e/guidePageSpec.cy.js
https://trello.com/c/6NJVU0yh/813-rf-guidepagespec-at008006-main-menu-guide-verify-the-text-weather-data-in-a-fast-and-easy-to-use-way-is-displayed
=> RF | GuidePageSpec> AT_008.006 | Main menu > Guide > Verify The text "Weather data in a fast and easy-to-use way" is displayed.

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/widgetsPageSpec.cy.js, cypress/fixtures/widgetsPage.json, cypress/pageObjects/ApiKeysPage.js, cypress/pageObjects/Footer.js, cypress/pageObjects/Header.js, cypress/pageObjects/WidgetsPage.js, cypress/support/commands.js
https://trello.com/c/OBkmkGyJ/642-at021004-footer-widgets-the-widgets-code-is-visible
=> RF | AT_021.004 Widgets > The widget's code is visible

cypress/e2e/OLD/arkGroup.cy.js, cypress/e2e/footerSpec.cy.js
https://trello.com/c/c6duVNkB/816-rf-specname-testname
=> RF | footerSpec> AT_030.002 | Footer > After clicking on the Website terms and conditions user navigated to a new pdf file page -POM

cypress/e2e/OLD/asiaJS.cy.js, cypress/e2e/paymentPageSpec.cy.js, cypress/fixtures/asiaJS.json, cypress/fixtures/url.json, cypress/pageObjects/Header.js
https://trello.com/c/NYeIGn4g/823-rf-paymentpagespec-at042005-user-page-my-paymentsverify-that-text-displays-on-the-page
=> RF | paymentPageSpec > AT_042.005 > User page >My payments>Verify that text displays on the page

cypress/e2e/mainPageSpec.cy.js, cypress/fixtures/mainPage.json, cypress/pageObjects/MainPage.js
https://trello.com/c/2QmEQ06Q/826-at037001-main-page-maps-verify-openstreetmapc-link
=> AT_037.001 | Main page [maps] > Verify " OpenStreetMap"(c) link

cypress/e2e/mainPageSpec.cy.js, cypress/fixtures/mainPage.json, cypress/fixtures/titles.json, cypress/fixtures/url.json, cypress/pageObjects/MainPage.js
https://trello.com/c/KD2EEe4P/829-at037002-main-page-maps-verify-clicking-on-the-copyright-sign
=> AT_037.002 | Main page [maps] > Verify clicking on the copyright sign

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/footerSpec.cy.js, cypress/pageObjects/Footer.js
https://trello.com/c/EWG83cfu/831-rf-footer-at022001-footer-verification-of-displayed-six-social-media-icons
=> RF | Footer > AT_022.001 | Footer > Verification of displayed six Social Media icons

cypress/e2e/mainPageSpec.cy.js, cypress/fixtures/mainPage.json, cypress/fixtures/solarRadiationPage.json, cypress/pageObjects/MainPage.js, cypress/pageObjects/SolarRadiationPage.js
https://trello.com/c/foUYsV8U/759-at055001-main-page-our-new-product-solar-radiation-api
=> AT_055.001 | Main page > Our new product > Solar Radiation API (POM)

cypress/e2e/apiKeysPageSpec.cy.js, cypress/e2e/userHomePageSpec.cy.js, cypress/e2e/widgetsPageSpec.cy.js, cypress/support/commands.js
trello: https://trello.com/c/6rjZBB9b 
files changed:
* commands.js
* apiKeysPageSpec.cy.js
* userHomePageSpec.cy.js
* widgetsPageSpec.cy.js
=> RF | Commands.js > Delete all login methods > delete method 'login'

cypress/e2e/OLD/group_javascript_for_qas.cy.js, cypress/e2e/mainPageSpec.cy.js
https://trello.com/c/VakhvN2y/848-rf-at005004-verify-the-websites-name-and-description-is-correct-and-visible
=> Refactored AT_005.004 Verify the website’s name and description

cypress/e2e/OLD/BugHunters.cy.js, cypress/e2e/guidePageSpec.cy.js, cypress/fixtures/pricingPage.json, cypress/fixtures/url.json, cypress/pageObjects/GuidePage.js, cypress/pageObjects/PricingPage.js
https://trello.com/c/YsOblfWJ/822-rf-guidepagespec-guide-verify-the-button-subscribe-to-one-call-by-call-is-clickable-and-user-be-redirected-new-url
=> RF | guidePageSpec > AT_008.004 > Main page > Guide > Verify the button "Subscribe to One Call by Call" and url

cypress/e2e/OLD/noGroup.cy.js, cypress/e2e/signInPageSpec.cy.js, cypress/fixtures/signInPage.json, cypress/pageObjects/SignInPage.js
https://trello.com/c/T6I9GUEd/772-rf-singinpage-at006005-sign-in-sign-in-to-your-account-verify-that-after-the-user-fills-in-the-wrong-password-the-alert-pop-up-a
=> RF | singInPage > AT_006.005 | Sign in > Sign in to Your Account > Verify that after the user fills in the wrong password the alert pop-up appears

cypress/e2e/OLD/group_javascript_for_qas.cy.js, cypress/e2e/mainPageSpec.cy.js, cypress/fixtures/mainPage.json, cypress/pageObjects/MainPage.js
https://trello.com/c/viDENJYs/844-rf-main-page-at004001-main-page-verify-the-temperature-can-be-switched-from-imperial-to-metric
=> RF |MainPageSpec|AT_004.001 |Verify the temperature can be switched from Imperial to Metric

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/apiKeysPageSpec.cy.js, cypress/fixtures/apiKeysPage.json, cypress/pageObjects/ApiKeysPage.js
https://trello.com/c/MmHzWfP2/818-rf-at041002-user-my-api-keys-verify-that-user-can-navigate-to-api-keys-page-and-see-alert-info-message
=> RF | AT_041.002 | User > My API keys > Verify that user can navigate to api keys page and see alert info message

cypress/e2e/OLD/BugHunters.cy.js, cypress/e2e/guidePageSpec.cy.js, cypress/fixtures/guidePage.json, cypress/pageObjects/GuidePage.js
https://trello.com/c/u1YJxgcQ/856-rf-guidepagespec-at008009-main-menu-guide-verify-text-on-the-page
=> RF | guidePageSpec > AT_008.009 > Guide > Verify text on the page

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/partnersPageSpec.cy.js, cypress/fixtures/url.json, cypress/pageObjects/PartnersPage.js, cypress/pageObjects/PluginsWPCloudyPage.js
https://trello.com/c/LNvBog6F/858-rf-parterspagespec-at012006-partners-cms-verify-view-plugin-button-for-wordpress-wpcloudy-plugin
=> RF | PartnersPageSpec > AT_012.006 | Partners > CMS > Verify “View plugin” button for WordPress WPCloudy Plugin

cypress/e2e/OLD/ltByJs.cy.js, cypress/e2e/paymentPageSpec.cy.js, cypress/fixtures/paymentsPage.json, cypress/fixtures/signInPage.json, cypress/pageObjects/PaymentPage.js
https://trello.com/c/zyOlj87g/862-rf-specname-testname
=> RF_AT_042.004_transferToPom

cypress/e2e/OLD/arkGroup.cy.js
https://trello.com/c/r28f8KKF/832-tc001006-main-page-section-with-search-verify-that-the-city-of-copenhagen-is-displayed
=> AT_001.006 | Main page > Section with search > Verify that the city of Copenhagen is displayed.

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/footerSpec.cy.js, cypress/fixtures/footer.json, cypress/fixtures/url.json, cypress/pageObjects/Footer.js
https://trello.com/c/GEpYx8TI/860-rf-footer-at022002-footer-ensure-facebook-icon-redirection
=> RF | Footer > AT_022.002 | Footer > Ensure Facebook icon redirection to POM

cypress/e2e/OLD/Reporter.cy.js
https://trello.com/c/2ctT7IUg/835-rf-tests-from-folder-old
=> RF | Reporter | Tests from folder OLD > Add {force: true} to methods

cypress/e2e/mainPageSpec.cy.js
https://trello.com/c/zc9SKjfE/863-rf-mainpagespec-at001001-at001008-align-row-methods-into-one-column
=> RF | MainPageSpec > AT_001.001 & AT_001.008 Align row methods into one column

cypress/e2e/questionsPageSpec.cy.js, cypress/pageObjects/QuestionsPage.js
https://trello.com/c/MucmWfeY/868-rf-questionspagespec-at015001-add-method
=> RF | questionsPageSpec > AT_015.001 add method

cypress/e2e/OLD/arkGroup.cy.js, cypress/e2e/mapsPageSpec.cy.js, cypress/fixtures/mapsPage.json, cypress/fixtures/url.json
https://trello.com/c/j2eiMbk2/864-rf-mapspagespec-at027003-pom
=> RF | mapsPageSpec > AT_027.003> POM

cypress/e2e/faqPageSpec.cy.js, cypress/e2e/headerSpec.cy.js, cypress/fixtures/url.json
https://trello.com/c/hufHSAft/866-rf-faqpagespec-at016001-support-faq-page-verify-support-button-and-faq-link-is-clickable-and-redirects-to-the-faq-page
=> RF | FAQPageSpec > AT_016.001 | Support > FAQ page > Verify Support button and FAQ link is clickable and redirects to the FAQ page

cypress/e2e/OLD/asiaJS.cy.js, cypress/e2e/mainPageSpec.cy.js, cypress/pageObjects/MainPage.js
https://trello.com/c/dEpglRd6/875-rf-mainpage-at045008-main-page-section-with-8-day-forecast-see-the-weather-forecast-for-8-days
=> RF | MainPage > AT_045.008 | Main page > Section with 8-day forecast > See the weather forecast for 8 days

cypress/e2e/userHomePageSpec.cy.js, cypress/e2e/userPageBillingPlanSpec.cy.js, cypress/pageObjects/UserHomePage.js, cypress/pageObjects/UserPageBillingPlan.js, cypress/support/commands.js
https://trello.com/c/6rjZBB9b/836-rf-commandsjs-delete-all-login-methods
PLEASE DO NOT MERGE THIS REQUEST BEFORE #477 AND #478 THANK YOU
=> RF | Commands.js > Delete all login methods

cypress/e2e/userHomePageSpec.cy.js
https://trello.com/c/9e7ziBTl/872-rf-userhomepagespec-changed-singin-method
=> RF | userHomePageSpec > changed singIn method

cypress/e2e/userHomePageSpec.cy.js, cypress/e2e/userPageBillingPlanSpec.cy.js, cypress/pageObjects/UserHomePage.js, cypress/pageObjects/UserPageBillingPlan.js
https://trello.com/c/BN6fYmaY/834-rf-userpagebillingplanspec-changed-singin-method-and-elements-transfer
=> RF | userPageBillingPlanSpec > changed singIn method and elements transfer

cypress/e2e/signInPageSpec.cy.js
https://trello.com/c/aTWFP6pK/871-rf-singinpage-at006005-singin-method-added
=> RF | singInPage > AT_006.005 | singIn method added

cypress/e2e/businessPageSpec.cy.js, cypress/fixtures/mainAboutPage.json, cypress/fixtures/url.json, cypress/pageObjects/MainAboutUsPage.js
https://trello.com/c/OHXKGj2S/788-rf-at038002-about-us-verify-the-button-redirects
=> RF |AT_038.002 | About us > Verify the button redirects

cypress/e2e/guidePageSpec.cy.js, cypress/e2e/headerSpec.cy.js, cypress/fixtures/guidePage.json
https://trello.com/c/M2bEMFLY/877-rf-moving-at008007-to-headerspec-file
=> RF | moving AT_008.007 to headerSpec file

cypress/e2e/widgetsPageSpec.cy.js, cypress/fixtures/widgetsPage.json, cypress/pageObjects/ApiKeysPage.js, cypress/pageObjects/WidgetsPage.js
https://trello.com/c/ku29rocF/851-at021007-footer-widgetsverify-popup-window-with-info-appears-after-clicking-get-code-button
=> AT_021.007 | Footer > Widgets>Verify popup windows with info appear after clicking "Get code" buttons

cypress/e2e/OLD/BugHunters.cy.js
https://trello.com/c/IBWnwBpe/625-at042001-user-page-my-paymentsgo-to-the-page-payments
=> AT_042.001 | | User page >My payments>Go to the page /paymentsd test

cypress/e2e/OLD/BugHunters.cy.js, cypress/e2e/mainPageSpec.cy.js, cypress/fixtures/bugHunters.json, cypress/pageObjects/MainPage.js
https://trello.com/c/o9eQKBMZ/880-rf-mainpagespec-at001013-main-page-search-section-verify-search-city-valid-input-shows-dropdown
=> RF | mainPageSpec > AT_001.013 | Main page > Search section > Verify "Search City" valid input shows dropdown'

cypress/e2e/OLD/ltByJs.cy.js, cypress/e2e/headerSpec.cy.js, cypress/fixtures/howToStartPage.json, cypress/fixtures/url.json, cypress/pageObjects/Header.js, cypress/pageObjects/HowToStartPage.js
https://trello.com/c/7QrtuFFN/874-rf-headerspec-at018002-pom
=> RF | AT_018.002 | Support > Dropdown menu > Verify "How to start" menu link_POM

cypress/e2e/apiPageSpec.cy.js, cypress/e2e/mainPageSpec.cy.js, cypress/pageObjects/MainPage.js, cypress/pageObjects/TopicPage.js
https://trello.com/c/E57mAt5L/881-rf-mainpagespec-at051002-transfer-to-apipagespec-and-create-topicpagejs
=> RF | mainPageSpec | AT_051.002 > transfer to apiPageSpec and create TopicPage.js

cypress/e2e/userHomePageSpec.cy.js, cypress/pageObjects/UserHomePage.js
https://trello.com/c/HTCCAXPq/882-rf-userhomepage-at043004-method-changed
=> RF | userHomePage | AT_043.004 > method changed

cypress/e2e/OLD/asiaJS.cy.js, cypress/support/commands.js
https://trello.com/c/6rjZBB9b/836-rf-commandsjs-delete-all-login-methods
=> RF | Commands.js > Delete all login methods >AsiaJS

cypress/e2e/OLD/asiaJS.cy.js, cypress/e2e/mainPageSpec.cy.js, cypress/fixtures/mainPage.json, cypress/pageObjects/MainPage.js
https://trello.com/c/b1bwOFhL/876-rf-mainpage-at045009-main-page-section-with-8-day-forecast-detailed-weather-for-each-of-these-days-is-displayed
=> RF | MainPage > AT_045.009 | Main page > Section with 8-day forecast > Detailed weather for each of these days is displayed

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/guidePageSpec.cy.js, cypress/fixtures/url.json, cypress/pageObjects/GuidePage.js
https://trello.com/c/PRJSYaHQ/820-rf-guidepagespec-at008002-main-menu-guide-verify-the-first-button-learn-more-is-clickable-and-user-will-be-redirected-new-url
=> RF | guidePageSpec > AT_008.002 | Main menu > Guide | Verify the first button "Learn more" is clickable and user will be redirected new url

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/footerSpec.cy.js, cypress/fixtures/footer.json, cypress/pageObjects/Footer.js
https://trello.com/c/YMmkUwKg/861-rf-footer-at022003-footer-verify-twitter-icon-redirection
=> RF | Footer > AT_022.003 | Footer > Verify Twitter icon redirection

cypress/e2e/questionsPageSpec.cy.js
https://trello.com/c/EkoTd6yy/879-rf-questionspagespec-at014004-support-ask-a-question-the-captcha-error-message-is-displayed
=> RF | questionsPageSpec > AT_014.004 | Support > Ask a question > The captcha error message is displayed

cypress/e2e/OLD/Reporter.cy.js, cypress/e2e/headerSpec.cy.js, cypress/fixtures/mapsPage.json, cypress/fixtures/url.json
https://trello.com/c/WZDsyWQt/870-rf-at033012-header-navigation-verify-maps-menu-link
=> RF | headerSpec > AT_033.012 | Header > Navigation > Verify "Maps" menu link

cypress/e2e/mainPageSpec.cy.js, cypress/e2e/questionsPageSpec.cy.js
https://trello.com/c/zIjlQKqx/843-at014001-support-ask-a-question-after-not-checking-recaptcha-the-error-message-appears
=> RF | questionsPage refactoring

cypress/e2e/headerSpec.cy.js, cypress/fixtures/url.json
https://trello.com/c/jYqEQBlB/888-err-at-018002
=> ERR |  AT_018.002 header

cypress/e2e/widgetsPageSpec.cy.js, cypress/fixtures/widgetsPage.json, cypress/pageObjects/ApiKeysPage.js, cypress/pageObjects/WidgetsPage.js
https://trello.com/c/bVPb3Fnh/897-rf-widgetspagespect-at021004
=> RF | WidgetsPageSpect > AT_021.004  refactor methods

cypress/e2e/blogPageSpec.cy.js, cypress/pageObjects/BlogPage.js
https://trello.com/c/dwR6VQ6L/887-rf-blogpagespec-at013009-blog-weather-all-posts-links-are-clickable-and-redirect-a-user-to-the-posts-in-a-new-page
=> RF | blogPageSpec > AT_013.009 | Blog > Weather > All posts links are clickable and redirect a user to the posts in a new page

cypress/e2e/partnersPageSpec.cy.js, cypress/e2e/widgetsPageSpec.cy.js
https://trello.com/c/2h7gb4Tg/905-err-skip-partners-page-test-suite-at012002-verify-see-on-the-website-button
https://trello.com/c/hsL7ykSG/908-err-skipat021007-footer-widgets-verify-popup-windows
=> ERR skip  | Partners page test suite AT_012.002  and  'AT_021.007 Footer > Widgets> Verify popup windows

cypress/e2e/footerSpec.cy.js, cypress/e2e/widgetsPageSpec.cy.js, cypress/pageObjects/Footer.js
https://trello.com/c/5rzUhrTb/840-rf-footerspec-at022004-delete-the-second-assertion
=> RF | FooterSpec > AT_022.004 > Delete the second assertion

cypress/e2e/signInPageSpec.cy.js, cypress/pageObjects/Header.js, cypress/pageObjects/SignInPage.js
https://trello.com/c/7FWUZjxy/904-rf-headerspeccy-at020004-sign-indropdown-menuverify-dropdown-menu-is-visible-and-exist
=> RF | headerSpec.cy > AT_020.004 | Sign in>Dropdown menu>Verify dropdown menu is visible and exist

cypress/e2e/headerSpec.cy.js, cypress/e2e/ourInitiativesSpec.cy.js, cypress/e2e/widgetsPageSpec.cy.js
https://trello.com/c/9XcHR4dG/910-rf-headerspec-at002006-our-initiatives-verifying-the-websites-logo-is-clickable-and-redirects-user-to-the-main-page
=> RF | HeaderSpec > AT_002.006 | Our Initiatives > Verifying the website's logo is clickable and redirects User to the Main page

cypress/e2e/userHomePageSpec.cy.js, cypress/fixtures/signInPage.json, cypress/fixtures/userHomePage.json, cypress/pageObjects/Header.js, cypress/pageObjects/UserHomePage.js
https://trello.com/c/iJIHXNP0/916-rf-userhomepagespec-at032003-header-account-dropdown-menu-my-profile-password-change-verify-successful-password-change
=> RF | userHomePageSpec > AT_032.003 | Header > Account Dropdown Menu > My Profile > Password Change > Verify successful password change

cypress/e2e/paymentPageSpec.cy.js, cypress/fixtures/signInPage.json
https://trello.com/c/mltkwaZV/637-at042002-user-page-my-paymentsverify-that-text-displayed-on-the-page
=> AT_042.002 | User page >My payments>Verify that text displayed on the page

cypress/e2e/marketplacePageSpec.cy.js
https://trello.com/c/XhviwhaZ/919-rf-marketplace-verification-of-displayed-documentation-button-for-history-bulk
=> RF | Marketplace > Verification of displayed "Documentation" button for History bulk

cypress/e2e/businessPageSpec.cy.js, cypress/e2e/headerSpec.cy.js
https://trello.com/c/ClogpyMm/885-rf-at034001-header-verify-for-business-button-2
=> RF | AT_034.001 | Move to Header > verify "For Business" button - 3

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/headerSpec.cy.js
https://trello.com/c/oyFJyZj1/884-rf-headerspec-header-clicking-the-logo-verify-that-the-logo-is-clickable
=> RF | headerSpec > Header > Clicking the logo > Verify that the logo is clickable

cypress/e2e/headerSpec.cy.js
https://trello.com/c/zg90XglL/921-rf-at002008-dashboard-verifying-the-websites-logo-is-clickable-and-redirects-user-to-the-main-page-pom
=> RF | AT_002.008 | Dashboard > Verifying the website's logo is clickable and redirects User to the Main page > POM

cypress/e2e/userHomePageSpec.cy.js, cypress/fixtures/userHomePage.json, cypress/pageObjects/Header.js
https://trello.com/c/QxrAgOse/907-rf-at020001-userhomepagespec-sign-in-dropdown-menu-verify-dropdown-menu-options
=> RF | AT_020.001 | Sign in > Dropdown menu > Verify dropdown menu options (POM)

cypress/e2e/guidePageSpec.cy.js, cypress/e2e/topicPageSpec.cy.js
=> RF | 008.011 | Move to TopicPage >  Main menu > Guide > verify button "Home"

cypress/e2e/signInPageSpec.cy.js
https://trello.com/c/MxoHtmEj/925-rf-signinpagespec-at054002-personalaccountname-verify-a-successful-sign-out
=> RF |  signInPageSpec >AT_054.002 | PersonalAccountName > Verify a successful Sign-out

cypress/e2e/OLD/BugHunters.cy.js
https://trello.com/c/ludhzRrE/853-at009009-main-menu-marketplace-verifying-that-history-bulk-item-is-displayed
=> AT_009.009 | Main menu > Marketplace> Verifying that History bulk item is displayed

cypress/e2e/blogPageSpec.cy.js, cypress/e2e/headerSpec.cy.js
https://trello.com/c/jkbs005a/924-rf-headerspec-at013001-header-after-clicking-the-blog-menu-user-is-redirected-to-the-blog-page
=> RF | headerSpec > AT_013.001 | Header > After clicking the Blog menu User is redirected to the Blog page

cypress/e2e/footerSpec.cy.js
https://trello.com/c/E3tgMb6D/926-rf-footerspec-at050003-footer-the-user-is-redirected-to-terms-and-conditions-of-sale-page
=> RF | footerSpec > AT_050.003 | Footer > The User is redirected to Terms and conditions of sale page

cypress/e2e/signInPageSpec.cy.js, cypress/fixtures/signInPage.json, cypress/pageObjects/SignInPage.js
https://trello.com/c/3YNKhSBu/395-at032001-sign-in-my-profile-tab-menu-verify-password-change
=> AT_032.001 | Sign in > My profile Tab menu > Verify Password Change'

cypress/e2e/blogAgroPageSpec.cy.js, cypress/pageObjects/BlogAgroPage.js, cypress/pageObjects/BlogPage.js
https://trello.com/c/gOgL8ou7/913-at013011-blog-weather-agro-verify-that-all-posts-on-the-page-have-agro-category-in-description
=> AT_013.011 | Blog > Weather > AGRO > Verify that all posts on the page have "agro" category in description

cypress/e2e/widgetsPageSpec.cy.js, cypress/pageObjects/ApiKeysPage.js, cypress/pageObjects/WidgetsPage.js
https://trello.com/c/4jm0uVnC/930-at000000-name
=> AT_021_008_Widgets > The widget's code is visible

cypress/e2e/OLD/group_javascript_for_qas.cy.js, cypress/e2e/userPageBillingPlanSpec.cy.js
https://trello.com/c/dN7rV7do/902-rf-at048001-user-page-billing-plans-verify-page
=> RF | AT_048.001 | User page > Billing plans > Verify page

cypress/e2e/aboutUsPageSpec.cy.js
https://trello.com/c/uVNbDp09/898-rf-at028001-about-us-verify-about-us-link
=>  RF | AT_028.001 | About us > Verify "About us" link

cypress/e2e/footerSpec.cy.js, cypress/e2e/headerSpec.cy.js
https://trello.com/c/a90g7dNM/934-rf-headerspec-at002002-verifying-the-websites-logo-is-clickable-and-it-redirects-a-user-to-the-main-page
=> RF | headerSpec > AT_002.002 Verifying the website's logo is clickable and it redirects a User to the Main page

cypress/e2e/OLD/Reporter.cy.js, cypress/e2e/headerSpec.cy.js, cypress/fixtures/titles.json, cypress/pageObjects/Header.js, cypress/pageObjects/TopicPage.js
https://trello.com/c/GnReEk05/938-rf-at033013-header-navigation-verify-pricing-menu-link
=> AT_033.013 | Header > Navigation > Verify "Pricing" menu link

cypress/e2e/widgetsPageSpec.cy.js, cypress/pageObjects/MainPage.js, cypress/pageObjects/WidgetsPage.js
https://trello.com/c/Nu2LMJgJ/940-rf-widgetpagespec-at-024001-different-weather-option-verify-email-enter
=> Om/refactor at024.001 pom

cypress/e2e/OLD/group_javascript_for_qas.cy.js, cypress/e2e/footerSpec.cy.js, cypress/pageObjects/Footer.js
https://trello.com/c/d2gDfFzl/939-rf-at023001-footer-faq-verify-faq-link-redirects-to-the-corresponding-page
=> RF | AT_023.001 | Footer > FAQ > Verify "FAQ" link redirects to the corresponding page

cypress/e2e/blogAgroPageSpec.cy.js, cypress/e2e/blogPlatformPageSpec.cy.js, cypress/fixtures/blogPage.json, cypress/pageObjects/BlogPage.js, cypress/pageObjects/BlogPlatformPage.js
https://trello.com/c/VhFKZYQF/937-at013012-blog-weather-platform-verify-that-all-posts-on-the-page-have-platform-category-in-description
=> AT_013.012 | blogPlatformPageSpec > Verify that all posts on the page have "platform" category in description

cypress/e2e/mainPageSpec.cy.js, cypress/pageObjects/MainPage.js
https://trello.com/c/JgV6eOyN/883-rf-005003-main-page-verifying-the-websites-name-and-description
=> RF | 005.003 | Main page > Verifying the website's name and description

cypress/e2e/widgetsPageSpec.cy.js, cypress/fixtures/url.json, cypress/fixtures/widgetsPage.json, cypress/pageObjects/WidgetsPage.js
https://trello.com/c/u0m73kCH/917-rf-widgetspec-at021001-footer-widgetsinvalid-api
=> RF | WidgetSpec > AT_021.001 | Footer > Widgets>Invalid API

cypress/e2e/OLD/asiaJS.cy.js, cypress/e2e/mainPageSpec.cy.js, cypress/pageObjects/MainPage.js
https://trello.com/c/Hn3L1pTt/946-rf-mainpagespec-at004003-main-page-section-with-search-verify-the-converted-temperature-in-c-is-correct
=> RF | mainPageSpec > AT_004.003 | Main page > Section with search > Verify the converted temperature in °C is correct

cypress/e2e/widgetsPageSpec.cy.js
https://trello.com/c/4jm0uVnC/930-at021008-footer-widgets-the-widgets-code-is-visible
=> AT_021.008_Footer> Widgets > The widget's code is visible

cypress/e2e/ourInitiativesSpec.cy.js, cypress/fixtures/titles.json, cypress/fixtures/url.json
https://trello.com/c/r9mZGEA5/947-rf-rf-ourinitiativesspec-at046004-main-page-our-initiatives-button-learn-more-page-has-text-student-initiative
=> RF | ourInitiativesSpec > AT_046.004 | Main page > Our initiatives > button "Learn more" > page has text Student initiativeRF 046.004

cypress/e2e/mainPageSpec.cy.js
https://trello.com/c/H40l4g63/948-rf-at005005-main-page-verifying-the-websites-description-is-correct-and-visible-pom
=> RF | AT_005.005 | Main page > Verifying the website's description is correct and visible > POM

cypress/e2e/footerSpec.cy.js
https://trello.com/c/i4I5FHtX/942-rf-footerspec-at023002-verify-faq-link-redirects-to-the-corresponding-page
=> RF | footerSpec > AT_023.002 Verify "FAQ" link redirects to the corresponding page

cypress/e2e/mapsPageSpec.cy.js, cypress/fixtures/mapsPage.json, cypress/pageObjects/MapsPage.js
https://trello.com/c/HYhGu4sH/950-rf-mapspagespec-at026004-maps-click-on-any-city-on-the-map-and-see-the-data
=> RF | mapsPageSpec > AT_026.004 > Click on any city on the map and see the data

cypress/e2e/guidePageSpec.cy.js
https://trello.com/c/uH5g39ZY/956-rf-guidepagespec-at008003-main-menu-guide-verify-the-link-on-the-page-guide
=> RF | GuidePageSpec > AT_008.003 > Main menu > Guide > Verify the link on the page 'Guide'

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/headerSpec.cy.js
https://trello.com/c/qJ2O5TLw/955-rf-at002003-header-change-to-pom
=> RF | AT_002.003 | Header > change to POM

cypress/e2e/questionsPageSpec.cy.js, cypress/fixtures/questionsPage.json, cypress/pageObjects/QuestionsPage.js
https://trello.com/c/OAuM0BGQ/957-rf-at015002-questionspage-verify-error-message-for-an-unauthorised-user-pom
=> RF | AT_015.002 | QuestionsPage > Verify error message for an unauthorised user > POM

cypress/e2e/marketplacePageSpec.cy.js, cypress/fixtures/url.json, cypress/pageObjects/HistoryBulksNewPage.js, cypress/pageObjects/MarketplacePage.js
https://trello.com/c/xDzG7tTj/959-rf-marketplace-verification-than-place-order-button-is-displayed-and-leads-to-url
=> RF |  Marketplace > Verification than "Place order" button is displayed and leads to URL'

cypress/e2e/guidePageSpec.cy.js, cypress/fixtures/guidePage.json, cypress/pageObjects/GuidePage.js
https://trello.com/c/e5MkaAHD/962-rf-at008012-guide-verify-subheaders-are-displayed-on-the-page-pom
=> RF | AT_008.012 | Guide > Verify subheaders are displayed on the page > POM

cypress/e2e/OLD/Reporter.cy.js, cypress/e2e/apiKeysPageSpec.cy.js, cypress/e2e/mainPageSpec.cy.js, cypress/fixtures/mainPage.json, cypress/pageObjects/MainPage.js
https://trello.com/c/LEArAVcX/963-rf-mainpagespec-at001006-main-page-section-with-search-verify-text-message-when-entering-special-characters
=> RF | mainPageSpec > AT_001.006 | Main page > Section with search > Verify text message when entering special characters

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/blogPageSpec.cy.js
https://trello.com/c/WXocnWpf/975-rf-blogpagespec-blog-weather-verify-that-after-clicking-the-blog-menu-a-user-is-redirected-to-the-blog-page
=> RF | blogPageSpec > Blog > Weather > Verify that after clicking the Blog menu a user is redirected to the blog page

cypress/e2e/headerSpec.cy.js, cypress/fixtures/header.json, cypress/pageObjects/Header.js
https://trello.com/c/a1gFqxH9/976-rf-headerspec-at033019-header-navigation-verify-support-dropdawn-menu-faq
=> RF | headerSpec > AT_033.019 | Header > Navigation > Verify "Support" dropdawn menu, FAQ

cypress/e2e/marketplacePageSpec.cy.js, cypress/pageObjects/HistoryBulksNewPage.js, cypress/pageObjects/MarketplacePage.js
https://trello.com/c/wUmYk23h/952-at061003-marketplace-historical-data-archives-historical-weather-data-by-state-verify-sorted-by-names
=> AT_061.003 | Marketplace > Historical Data Archives > Historical Weather Data by State > Verify sorted by names

cypress/e2e/mapsPageSpec.cy.js, cypress/fixtures/mapsPage.json, cypress/pageObjects/MapsPage.js
https://trello.com/c/FsiDpZAh/977-rf027003-mapspagespecmaps-section-with-the-scale-the-scale-in-the-lower-right-corner-changes-to-precipitation-mm-h
=> RF_027.003 | mapsPageSpec>Maps > Section with the scale >The scale in the lower right corner changes to "Precipitation, mm/h".

cypress/e2e/OLD/arkGroup.cy.js, cypress/e2e/mainPageSpec.cy.js, cypress/fixtures/mainPage.json
https://trello.com/c/7CX24nSO/984-rf-specname-at001017-main-page-section-with-search-verify-that-the-city-of-copenhagen-is-displayed
=> RF | mainPageSpec > AT_001.017 | Main page > Section with search > Verify that the city of Copenhagen is displayed.

cypress/e2e/signInPageSpec.cy.js
https://trello.com/c/Bw3WEA6f/918-rf-signinspec-at031002-sign-in-account-dropdown-menu-verify-user-is-able-to-log-out
=> RF | SignInSpec > AT_031.002 | Sign In > Account Dropdown Menu > Verify user is able to log out

cypress/e2e/dashboardPageSpec.cy.js, cypress/pageObjects/DashboardPage.js
https://trello.com/c/xzVAUUaC/990-rf-at025009-main-menu-dashboard-verify-the-first-button-try-the-dashboard-is-clickable-and-redirects-user-to-the-sign-in-page
=> RF | AT_025.009 | Dashboard > Verify the first button "Try the Dashboard" is clickable and redirects User to the Sign in page > POM

cypress/e2e/dashboardPageSpec.cy.js, cypress/fixtures/url.json, cypress/pageObjects/DashboardPage.js
https://trello.com/c/avCjo9e2/991-rf-at025010-main-menu-dashboard-verify-the-first-button-contact-us-is-clickable-and-redirects-user-to-the-questions-page
=> RF | AT_025.010 | Dashboard > Verify the first button "Contact us" is clickable and redirects User to the Questions page > POM

cypress/e2e/OLD/jScript_group.cy.js, cypress/e2e/headerSpec.cy.js
https://trello.com/c/Y6iDdAZy/992-rf-specname-testname
=> RF | HeaderSpec > AT_002.007 | Header > Verify that the website logo is clickable and the user is redirected to the Main Page

cypress/e2e/aboutUsPageSpec.cy.js, cypress/pageObjects/AboutUsPage.js
https://trello.com/c/QDpWRkpi/819-rf-specname-at0280002-footer-about-us-verify-contact-us-button-redirects-user-to-questions-page
=> RF | aboutUsPageSpec > AT_028.0002 | Footer > About us > Verify "Contact us" button redirects user to "Questions" page

cypress/e2e/OLD/asiaJS.cy.js, cypress/e2e/marketplacePageSpec.cy.js, cypress/fixtures/url.json, cypress/pageObjects/MarketplacePage.js
https://trello.com/c/jtIjASan/998-rf-at005005-main-page-verifying-the-websites-description-is-correct-and-visible
=> RF | AT_005.005 | Main page > Verifying the website's description is correct and visible

cypress/e2e/signInPageSpec.cy.js
https://trello.com/c/TVClKpm5/995-rf-sign-in-after-successful-sign-in-new-window-should-display-text-signed-in-successfully
=>  Sign in > After successful sign in new window should display text "Signed in successfully."'

cypress/e2e/userPageBillingPlanSpec.cy.js, cypress/fixtures/signInPage.json, cypress/fixtures/userPageBillingPlan.json, cypress/pageObjects/BillingPlansPage.js, cypress/pageObjects/UserHomePage.js
https://trello.com/c/aDtCrhPJ/1001-at048005-user-page-billing-plans-verify-information-about-billing-plans-is-available
=> AT_048.005 | User page > Billing plans > Verify information about billing plans is available

cypress/e2e/headerSpec.cy.js
https://trello.com/c/6ntKW5EZ/961-rf-headerspec-at00800602-verify-the-text-openweather-products-at00800602is-displayed
=> RF | headerSpec > AT_008.006.02 > Verify The text "OpenWeather products" AT_008.006.02is displayed

cypress/e2e/OLD/arkGroup.cy.js, cypress/e2e/headerSpec.cy.js, cypress/fixtures/header.json
https://trello.com/c/tEgTCx0Y/889-rf-headerspec-at039002-personalaccountname-checking-for-options-in-account-dropdown-menu-pom
=> RF | headerSpec > AT_039.002 | PersonalAccountName > Checking for options in account dropdown menu

cypress/e2e/marketplacePageSpec.cy.js
https://trello.com/c/K40IKSqh/994-at061006-marketplace-historical-data-archives-historical-weather-data-by-state-verify-that-the-price-for-each-state-is-correct
=> AT_061.006 | Marketplace > Historical Data Archives > Historical Weather Data by State > Verify that the price for each state is correct

cypress/e2e/historicalWeatherDataByStateSpec.cy.js, cypress/pageObjects/HistoricalWeatherDataByStatePage.js
https://trello.com/c/PriOLlCC/1005-at061007-historical-weather-data-by-state-verify-each-state-has-an-appropriate-zip-code
=> AT_061.007 | Historical Weather Data by State > Verify each state has an appropriate ZIP code

cypress/e2e/api_testing/artDiuzhikovSpec.cy.js, cypress/fixtures/apiData.json
Created a new file for API testing with 5 tests in there:
- Verify the status of the response;
- Verify the booking ID;
- Verify the format of "check in date" key;
- Verify the format of "check out date" key;
- Verify the type of "deposit paid" key.
Also added some data to the fixture file.
=> API | artDiuzhikovSpec | Get a booking test suite

cypress/e2e/api_testing/artDiuzhikovSpec.cy.js
Added a new test suite to the spec file with 3 tests in there:
- Verify the status of the booking creation;
- Verify the last name in the latest created booking;
- Verify the price in the latest created booking.
=> API | artDiuzhikovSpec | Create a booking test suite

cypress/e2e/mapsPageSpec.cy.js, cypress/pageObjects/MapsPage.js
https://trello.com/c/6cbzV7Ed/1006-rf-maps-section-with-the-scale-the-scale-s-name-matches-the-label-s-name-after-selecting-wind-speed
=> RF | Maps > Section with the scale > The scale\s name matches the label\s name after selecting "Wind speed"'

cypress/e2e/api_testing/artDiuzhikovSpec.cy.js, cypress/e2e/api_testing/nadiaKoluzaevaSpec.cy.js, cypress/e2e/widgetsPageSpec.cy.js
https://trello.com/c/n3MNxMlX/1008-err-artdiuzhikovspec-api-testing-with-cypress
https://trello.com/c/WUQeMdBk/1007-err-widgetspagespec-at021007-footer-widgets-verify-popup-windows-with-info-appear-after-clicking-get-code-buttons
=> API | nadiaKoluzaevaSpec > API with Cypress > Create Token

cypress/e2e/api_testing/artDiuzhikovSpec.cy.js, cypress/e2e/api_testing/olgabyrSpec.cy.js, cypress/fixtures/apiData.json
Refactor code includes:
1) added fixtures 
2) changed delete method from basic authorization (no token needed) to delete using token authorization
=> PF| API | OlgaByR > Create and delete booking with token autorization

cypress/e2e/api_testing/artDiuzhikovSpec.cy.js, cypress/fixtures/apiData.json
https://trello.com/c/n3MNxMlX/1008-err-artdiuzhikovspec-api-testing-with-cypress
=> ERR | artDiuzhikovSpec > API testing with Cypress

cypress/e2e/mapsPageSpec.cy.js, cypress/pageObjects/MapsPage.js
https://trello.com/c/jn1yuu79/1011-at026005-maps-verify-search-city-works-correctly-happy-path
=> AT_26.005 | Maps > Verify search city works correctly Happy path

cypress/e2e/api_testing/olgabyrSpec.cy.js, cypress/fixtures/apiData.json
Refactoring includes:
1) changed all code  lines with https://restful-booker.herokuapp.com/  using  const API_BASE_URL
2) changed response status codes with fixtures data
=> RF | API | OlgaByRSpec> Create and delete booking with token authorization

cypress/e2e/api_testing/lauraBSpec.cy.js
=> API | lauraBSpec | Create API Tests

cypress/e2e/api_testing/svetlanaKanelApiSpec.cy.js
All methods remove to the first describe and some logs are deleted
=> RF | svetlanaKanelApiSpec

cypress/e2e/api_testing/liliiaFadeevaSpec.cy.js
=> API | liliiaFadeevaSpec | Create a booking test suite

cypress/e2e/api_testing/lauraBSpec.cy.js
Created, Delete booking, token
=> API | lauraBSpec > Create, Delete booking, token

cypress/e2e/api_testing/sanaGreenSpec.cy.js
=> API|sanaGreen|First API test - Auth

cypress/e2e/api_testing/anzhelaKhakunovaSpec.cy.js, cypress/fixtures/apiData.json
=> API | anzhelaKhakunovaSpec

cypress/e2e/signInPageSpec.cy.js, cypress/e2e/userMyProfilePageSpec.cy.js, cypress/pageObjects/SignInPage.js, cypress/pageObjects/UserHomePage.js, cypress/pageObjects/UserMyProfilePage.js
https://trello.com/c/l2fqZfwc/1013-rf-at032001-sign-in-my-profile-tab-menu-verify-password-change
=> RF | AT_032.001 | Sign in > My profile Tab menu > Verify Password Change'

cypress/e2e/historicalWeatherDataByStateSpec.cy.js
https://trello.com/c/IbYKHLhW/1018-at061008-historical-weather-data-by-state-verify-each-state-has-its-own-zip-code-and-particular-price
=> AC_061.008_Historical Weather Data by State_ Table

cypress/e2e/apiPageSpec.cy.js, cypress/e2e/topicPageSpec.cy.js
https://trello.com/c/l9uS8uI4/1014-rf-at051002-main-menu-api-testing-the-home-link-redirected-to-the-home-page
=> RF | AT_051.002 | Main menu > API > Testing the "Home" link redirected to the Home page'

cypress/e2e/userPageBillingPlanSpec.cy.js, cypress/pageObjects/PricingPage.js
https://trello.com/c/Oz0Fs9Cd/1021-rf-at048004-at048004-user-page-billing-plans-verify-that-the-link-one-call-by-call-subscription-plan-open-a-new-page-url
=> RF | AT_048.004 | User page > Billing plans > Verify that the link "One Call by Call" subscription plan" open a new page url.

cypress/e2e/api_testing/svetlanaKanelApiSpec.cy.js
add fixture to partialUpdateBooking method
=> RF | svetlanaKanelApiSpec add fixture to partialUpdateBooking method

cypress/e2e/blogPageSpec.cy.js, cypress/fixtures/blogPage.json, cypress/pageObjects/BlogPage.js
https://trello.com/c/dwR6VQ6L/887-rf-blogpagespec-at013009-blog-weather-all-posts-links-are-clickable-and-redirect-a-user-to-the-posts-in-a-new-page
=> RF | AT_013.009 | Blog > Weather > All posts links are clickable and redirect a user to the posts in a new page

cypress/e2e/userPageBillingPlanSpec.cy.js, cypress/fixtures/userPageBillingPlan.json
https://trello.com/c/kfe4Jvt6/1028-rf-at048005-user-page-billing-plans-verify-information-about-billing-plans-is-available
=> RF | AT_048.005 | User page > Billing plans > Verify information about billing plans is available

cypress/e2e/historicalWeatherDataByStateSpec.cy.js, cypress/e2e/marketplacePageSpec.cy.js
https://trello.com/c/zGLg4KVg/1029-rf-at061003-marketplace-historical-data-archives-historical-weather-data-by-state-verify-sorted-by-names
=> RF | AT_061.003 | Marketplace > Historical Data Archives > Historical Weather Data by State > Verify sorted by names
